import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, Crown, Eye, FileClock, Flag, MessageSquare, ShieldCheck, Users } from 'lucide-react'
import { requireAdminPermission } from '@/lib/auth/authorization'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { DashboardEmptyState, DashboardPage, DashboardPageHeader, DashboardSection, DashboardStat, DashboardStatGrid } from '@/components/patterns/dashboard-page'
import { reviewAdminCommunityRequestAction, setAdminCommunityMemberRoleAction, transferCommunityOwnershipAction } from '../actions'

export default async function AdminCommunityDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { admin } = await requireAdminPermission('communities.manage')
  const [communityResult, membersResult, requestsResult, postsResult, reportsResult, auditResult] = await Promise.all([
    admin.from('communities').select('id,name,slug,description,address,is_private,posting_policy,created_at,created_by,platform_users!communities_created_by_fkey(full_name)').eq('id', id).maybeSingle(),
    admin.from('community_members').select('id,user_id,role,joined_at,platform_users(id,full_name,type)').eq('community_id', id).order('joined_at'),
    admin.from('community_join_requests').select('id,user_id,status,created_at,platform_users!community_join_requests_user_id_fkey(full_name)').eq('community_id', id).eq('status', 'pending').order('created_at'),
    admin.from('posts').select('id,content,created_at,user_id,post_comments(count)').eq('community_id', id).order('created_at', { ascending: false }).limit(30),
    admin.from('content_reports').select('id,reason,details,status,created_at,target_type,target_id').eq('target_type', 'community').eq('target_id', id).order('created_at', { ascending: false }),
    admin.from('audit_logs').select('id,action,user_email,new_data,created_at').eq('table_name', 'communities').eq('record_id', id).order('created_at', { ascending: false }).limit(30),
  ])
  if (communityResult.error || !communityResult.data) notFound()
  const community = communityResult.data
  const members = membersResult.data || []
  const requests = requestsResult.data || []
  const posts = postsResult.data || []
  const reports = reportsResult.data || []
  const audits = auditResult.data || []
  const owner = Array.isArray(community.platform_users) ? community.platform_users[0] : community.platform_users
  const adminCount = members.filter(member => member.role === 'admin').length

  return <DashboardPage>
    <DashboardPageHeader title={community.name} description="Governação administrativa, membros, pedidos, conteúdo sinalizado e histórico auditável." action={<div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href="/admin/comunidades"><ArrowLeft className="mr-2 h-4 w-4" />Comunidades</Link></Button><Button asChild><Link href={`/comunidades/${community.slug || community.id}`} target="_blank"><Eye className="mr-2 h-4 w-4" />Página pública</Link></Button></div>} />
    <DashboardStatGrid><DashboardStat label="Membros" value={members.length} href="#membros" icon={<Users className="h-5 w-5" />} /><DashboardStat label="Administradores" value={adminCount} href="#membros" icon={<Crown className="h-5 w-5" />} /><DashboardStat label="Pedidos" value={requests.length} href="#pedidos" icon={<ShieldCheck className="h-5 w-5" />} /><DashboardStat label="Denúncias" value={reports.filter(item => item.status === 'pending').length} href="#denuncias" icon={<Flag className="h-5 w-5" />} /></DashboardStatGrid>

    <DashboardSection title="Identidade e responsabilidade" description="A transferência promove automaticamente o novo responsável a administrador e fica registada no audit log."><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><p className="text-sm font-semibold">{owner?.full_name || 'Responsável não identificado'}</p><p className="mt-1 text-sm text-muted-foreground">{community.is_private ? 'Comunidade privada' : 'Comunidade pública'} · {community.address || 'Online'}</p><p className="mt-3 text-sm">{community.description || 'Sem descrição.'}</p></div><form action={transferCommunityOwnershipAction.bind(null, id)} className="grid gap-3 rounded-xl border p-4"><label className="text-sm font-medium" htmlFor="new_owner_id">Transferir responsabilidade</label><select id="new_owner_id" name="new_owner_id" defaultValue="" className="min-h-11 rounded-lg border border-input bg-background px-3 text-sm" required><option value="" disabled>Selecionar membro</option>{members.filter(member => member.user_id && member.user_id !== community.created_by).map(member => <option key={member.id} value={member.user_id!}>{member.platform_users?.full_name || member.user_id}</option>)}</select><Input name="reason" minLength={5} maxLength={500} placeholder="Motivo obrigatório" required /><Button type="submit" variant="outline">Transferir</Button></form></div></DashboardSection>

    <div id="pedidos" className="scroll-mt-24"><DashboardSection title="Pedidos de adesão" description="Cada decisão exige motivo e fica registada.">{requests.length === 0 ? <DashboardEmptyState icon={<ShieldCheck className="h-10 w-10" />} title="Sem pedidos pendentes" description="Não existem pedidos por decidir." /> : <div className="space-y-3">{requests.map(request => <article key={request.id} className="grid gap-3 rounded-xl border p-4 lg:grid-cols-[minmax(0,1fr)_minmax(260px,420px)]"><div><p className="font-semibold">{request.platform_users?.full_name || 'Utilizador'}</p><p className="text-xs text-muted-foreground">Pedido em {new Date(request.created_at).toLocaleString('pt-PT')}</p></div><div className="grid gap-2"><form action={reviewAdminCommunityRequestAction.bind(null, id, request.id, 'approved')} className="flex gap-2"><Input name="reason" minLength={5} maxLength={500} placeholder="Motivo da aprovação" required /><Button type="submit">Aprovar</Button></form><form action={reviewAdminCommunityRequestAction.bind(null, id, request.id, 'rejected')} className="flex gap-2"><Input name="reason" minLength={5} maxLength={500} placeholder="Motivo da recusa" required /><Button type="submit" variant="outline">Recusar</Button></form></div></article>)}</div>}</DashboardSection></div>

    <div id="membros" className="scroll-mt-24"><DashboardSection title="Membros e moderadores" description="Alterações de função exigem justificação; nunca é permitido remover a última administração."><div className="grid gap-3 md:grid-cols-2">{members.map(member => <article key={member.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{member.platform_users?.full_name || 'Utilizador'}</p><p className="text-xs text-muted-foreground">{member.platform_users?.type || 'membro'} · desde {new Date(member.joined_at).toLocaleDateString('pt-PT')}</p></div><Badge variant={member.role === 'admin' ? 'default' : 'outline'}>{member.role === 'admin' ? 'Administrador' : 'Membro'}</Badge></div><form action={setAdminCommunityMemberRoleAction.bind(null, id, member.user_id!, member.role === 'admin' ? 'member' : 'admin')} className="mt-3 flex gap-2"><Input name="reason" minLength={5} maxLength={500} placeholder="Motivo obrigatório" required /><Button type="submit" variant="outline" size="sm" disabled={!member.user_id}>{member.role === 'admin' ? 'Retirar admin' : 'Tornar admin'}</Button></form></article>)}</div></DashboardSection></div>

    <DashboardSection title="Publicações recentes" description="Visão operacional do conteúdo; a remoção continua centralizada na fila de moderação.">{posts.length === 0 ? <DashboardEmptyState icon={<MessageSquare className="h-10 w-10" />} title="Sem publicações" description="A comunidade ainda não tem publicações." /> : <div className="space-y-3">{posts.map(post => <article key={post.id} className="rounded-xl border p-4"><p className="line-clamp-3 whitespace-pre-line text-sm">{post.content || 'Publicação sem texto'}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(post.created_at || '').toLocaleString('pt-PT')} · {post.post_comments?.[0]?.count || 0} comentários</p></article>)}</div>}</DashboardSection>

    <div id="denuncias" className="scroll-mt-24"><DashboardSection title="Denúncias da comunidade" description="A resolução é feita na moderação central para preservar uma única fila de confiança.">{reports.length === 0 ? <DashboardEmptyState icon={<Flag className="h-10 w-10" />} title="Sem denúncias" description="Não existem denúncias diretamente associadas a esta comunidade." /> : <div className="space-y-3">{reports.map(report => <article key={report.id} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-semibold">{report.reason}</p><Badge variant="outline">{report.status}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{report.details || 'Sem detalhes adicionais.'}</p></div><Button asChild variant="outline"><Link href="/admin/moderacao">Abrir moderação</Link></Button></article>)}</div>}</DashboardSection></div>

    <DashboardSection title="Histórico administrativo" description="Decisões sensíveis ficam associadas ao administrador, motivo e instante.">{audits.length === 0 ? <DashboardEmptyState icon={<FileClock className="h-10 w-10" />} title="Sem alterações administrativas" description="As próximas decisões aparecerão aqui." /> : <div className="space-y-2">{audits.map(audit => <article key={audit.id} className="rounded-xl border p-3"><p className="text-sm font-semibold">{audit.action}</p><p className="text-xs text-muted-foreground">{audit.user_email || 'Administrador'} · {new Date(audit.created_at || '').toLocaleString('pt-PT')}</p></article>)}</div>}</DashboardSection>
  </DashboardPage>
}
