'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getEffectiveEntitlement, getLimit } from '@/lib/billing/entitlements'
import { revalidatePath } from 'next/cache'

type CreateCommunityInput={name:string;description:string;privacy:string;city:string;categoryId:string;postingPolicy?:'members'|'reactions_only'|'admin_only';locationScope?:'online'|'local'|'regional'|'national';latitude?:number|null;longitude?:number|null}
export async function createCommunityAction(input:CreateCommunityInput){
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Precisa estar autenticado.');const admin=createAdminClient();const{data:profile,error:profileError}=await admin.from('platform_users').select('type').eq('id',user.id).maybeSingle();if(profileError)throw new Error('Não foi possível validar o seu perfil.');if(!profile?.type||!['professional','event_manager'].includes(profile.type))throw new Error('Apenas profissionais e gestores de eventos podem criar comunidades.')
 const createEntitlement=await getEffectiveEntitlement(user.id,'communities.create.enabled');if(createEntitlement&&!createEntitlement.unlimited&&createEntitlement.valueType==='boolean'&&createEntitlement.value!==true)throw new Error('O teu plano atual não permite criar comunidades. Atualiza para Pro ou Premium em Faturação.');const maxEntitlement=await getEffectiveEntitlement(user.id,'communities.max');if(maxEntitlement){const limit=await getLimit(user.id,'communities.max');if(limit!==null){const{count,error}=await admin.from('community_members').select('community_id',{count:'exact',head:true}).eq('user_id',user.id).eq('role','admin');if(error)throw new Error('Não foi possível validar o limite de comunidades.');if((count??0)>=limit)throw new Error(`Atingiste o limite de ${limit} comunidades do teu plano.`)}}
 const cleanName=String(input.name||'').trim(),description=String(input.description||'').trim(),address=String(input.city||'').trim().slice(0,180)||null;if(cleanName.length<3||cleanName.length>160)throw new Error('O nome da comunidade deve ter entre 3 e 160 caracteres.');if(description.length<10||description.length>5000)throw new Error('A descrição deve ter entre 10 e 5000 caracteres.');if(!input.categoryId)throw new Error('Seleciona uma modalidade.');const{data:category,error:categoryError}=await admin.from('categories').select('id,name,slug').eq('id',input.categoryId).maybeSingle();if(categoryError||!category)throw new Error('A modalidade selecionada já não está disponível.')
 const policy=['members','reactions_only','admin_only'].includes(String(input.postingPolicy))?input.postingPolicy!:'members';const scope=['online','local','regional','national'].includes(String(input.locationScope))?input.locationScope!:(address?'local':'online');const lat=Number(input.latitude),lng=Number(input.longitude);const latitude=Number.isFinite(lat)&&lat>=-90&&lat<=90?lat:null,longitude=Number.isFinite(lng)&&lng>=-180&&lng<=180?lng:null;const slugBase=cleanName.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)+/g,'')||'comunidade',slug=`${slugBase}-${crypto.randomUUID().slice(0,8)}`
 const{data:created,error:createError}=await admin.from('communities').insert({name:cleanName,slug,description,is_private:input.privacy==='priv',created_by:user.id,sport_category:category.name,posting_policy:policy,location_scope:scope,address,latitude,longitude}).select('id').single();if(createError||!created)throw new Error(createError?.message||'Erro ao criar comunidade.')
 const{error:memberError}=await admin.from('community_members').insert({community_id:created.id,user_id:user.id,role:'admin'});if(memberError){await admin.from('communities').delete().eq('id',created.id);throw new Error('Não foi possível atribuir o administrador. A operação foi revertida.')}
 const{error:relationError}=await (admin as any).from('community_categories').insert({community_id:created.id,category_id:category.id});if(relationError){await admin.from('community_members').delete().eq('community_id',created.id).eq('user_id',user.id);await admin.from('communities').delete().eq('id',created.id);throw new Error('Não foi possível associar a modalidade. A operação foi revertida.')}
 revalidatePath('/comunidades');revalidatePath('/dashboard/comunidades');revalidatePath(`/comunidades/${created.id}`);return{success:true,id:created.id}
}
