'use server'
import {revalidatePath} from 'next/cache'
import {createClient} from '@/lib/supabase/server'
import {createAdminClient} from '@/lib/supabase/admin'
import {autoConfirmAtFromNow,canMarkDelivered,releaseReservationSettlement} from '@/lib/billing/reservation-settlement'
async function user(){const s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)throw Error('Sessão inválida.');return user}
export async function markReservationDeliveredAction(id:string){const u=await user(),db=createAdminClient() as any,{data:r}=await db.from('reservations').select('id,user_id,professional_id,space_id,date,end_time,payment_status,service_delivery_status').eq('id',id).maybeSingle();if(!r)throw Error('Reserva não encontrada.');const owner=r.professional_id?(await db.from('professionals').select('user_id').eq('id',r.professional_id).maybeSingle()).data?.user_id:(await db.from('sport_spaces').select('owner_user_id').eq('id',r.space_id).maybeSingle()).data?.owner_user_id;if(owner!==u.id)throw Error('Sem permissão.');if(r.payment_status!=='paid'||r.service_delivery_status!=='scheduled')throw Error('A prestação não pode ser concluída neste estado.');if(!canMarkDelivered(r))throw Error('Só podes marcar como prestado depois do fim da reserva.');const now=new Date().toISOString(),{data:x,error}=await db.from('reservations').update({service_delivery_status:'awaiting_customer_confirmation',settlement_status:'held',provider_marked_completed_at:now,auto_confirm_after:autoConfirmAtFromNow(),updated_at:now}).eq('id',id).eq('service_delivery_status','scheduled').select('id').maybeSingle();if(error||!x)throw Error(error?.message||'Falha ao atualizar.');await db.from('reservation_delivery_events').insert({reservation_id:id,event_type:'provider_marked_delivered',actor_user_id:u.id});await db.from('notifications').insert({user_id:r.user_id,type:'reservation',message:'O prestador marcou o serviço como realizado. Confirma a prestação ou reporta um problema nas próximas 48 horas.',link:'/dashboard/confirmacoes',dedupe_key:`delivery:${id}:awaiting`});revalidatePath('/dashboard/reservas');revalidatePath('/dashboard/confirmacoes');return{success:true}}
export async function confirmReservationDeliveryAction(id:string){const u=await user(),db=createAdminClient() as any,now=new Date().toISOString(),{data:x,error}=await db.from('reservations').update({service_delivery_status:'completed',settlement_status:'eligible',athlete_confirmed_at:now,status:'completed',updated_at:now}).eq('id',id).eq('user_id',u.id).eq('service_delivery_status','awaiting_customer_confirmation').eq('settlement_status','held').select('id').maybeSingle();if(error||!x)throw Error(error?.message||'Já não está disponível para confirmação.');await db.from('reservation_delivery_events').insert({reservation_id:id,event_type:'athlete_confirmed',actor_user_id:u.id});await releaseReservationSettlement(id);revalidatePath('/dashboard/confirmacoes');revalidatePath('/dashboard/agenda');revalidatePath('/dashboard/reservas');return{success:true}}
export async function disputeReservationDeliveryAction(id:string,reason:string){const u=await user(),clean=String(reason||'').trim();if(clean.length<10||clean.length>2000)throw Error('Descreve o problema entre 10 e 2000 caracteres.');const db=createAdminClient() as any,now=new Date().toISOString(),{data:x,error}=await db.from('reservations').update({service_delivery_status:'disputed',settlement_status:'blocked',dispute_opened_at:now,dispute_reason:clean,updated_at:now}).eq('id',id).eq('user_id',u.id).eq('service_delivery_status','awaiting_customer_confirmation').eq('settlement_status','held').select('id').maybeSingle();if(error||!x)throw Error(error?.message||'Já não está disponível para contestação.');await db.from('reservation_delivery_events').insert({reservation_id:id,event_type:'athlete_disputed',actor_user_id:u.id,note:clean});revalidatePath('/dashboard/confirmacoes');revalidatePath('/dashboard/agenda');return{success:true}}
