import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Activity, Calendar, CalendarCheck, Heart, MessageSquare, ReceiptText, Star, UserRound, BriefcaseBusiness, ArrowRight, Building2, Clock3, CircleDollarSign } from 'lucide-react'
import type { PlatformRole } from '@/lib/auth/roles'
import { DashboardPage, DashboardPageHeader, DashboardSection, DashboardStat, DashboardStatGrid } from '@/components/patterns/dashboard-page'

type Props={role:PlatformRole;userId:string;displayName:string;entity?:any;entities?:any[];selectedEntityId?:string|null}
type Metric={label:string;value:string|number;icon:any;hint?:string}
type ActivityRow={id:string;title:string;subtitle:string;status?:string;amount?:number|null}
function dateLabel(date:string,time?:string|null){return`${new Date(`${date}T12:00:00`).toLocaleDateString('pt-PT')}${time?` · ${String(time).slice(0,5)}`:''}`}

export async function OverviewDashboard({role,userId,displayName,entity,entities=[],selectedEntityId}:Props){
 const supabase=await createClient();const[{count:unreadMessages},{data:recentMessages}]=await Promise.all([supabase.from('messages').select('id',{count:'exact',head:true}).eq('receiver_id',userId).is('read_at',null),supabase.from('messages').select('id,sender_id,content,created_at,read_at').eq('receiver_id',userId).order('created_at',{ascending:false}).limit(3)]);const senderIds=[...new Set((recentMessages||[]).map(m=>m.sender_id))];const{data:senders}=senderIds.length?await supabase.from('platform_users').select('id,full_name,type').in('id',senderIds):{data:[] as any[]};const senderMap=new Map((senders||[]).map(s=>[s.id,s]));const hasRecentMessages=(recentMessages||[]).length>0
 let metrics:Metric[]=[],activityTitle='Atividade recente',activityRows:ActivityRow[]=[],primaryHref='/pesquisa',primaryLabel='Explorar plataforma',nextAction:any=null
 if(role==='athlete'){
  const now=new Date().toISOString().slice(0,10);const[{count:favorites},{data:reservations},{data:participations}]=await Promise.all([supabase.from('favorites').select('id',{count:'exact',head:true}).eq('user_id',userId),supabase.from('reservations').select('id,professional_id,service_id,space_id,space_room_id,date,start_time,end_time,status,payment_status,amount').eq('user_id',userId).order('date',{ascending:true}).order('start_time',{ascending:true}).limit(200),supabase.from('event_participants').select('id,event_id,status,payment_status').eq('user_id',userId)])
  const upcoming=(reservations||[]).filter(r=>r.date>=now&&!['cancelled','completed'].includes(String(r.status)));const paid=(reservations||[]).filter(r=>r.payment_status==='paid'||['paid','completed'].includes(String(r.status)));const proIds=[...new Set(upcoming.map(r=>r.professional_id).filter((id):id is string=>Boolean(id)))],serviceIds=[...new Set(upcoming.map(r=>r.service_id).filter((id):id is string=>Boolean(id)))],spaceIds=[...new Set(upcoming.map(r=>r.space_id).filter((id):id is string=>Boolean(id)))];const[{data:pros},{data:services},{data:spaces}]=await Promise.all([proIds.length?supabase.from('professionals').select('id,full_name,professional_name').in('id',proIds):Promise.resolve({data:[] as any[]}),serviceIds.length?supabase.from('services').select('id,name').in('id',serviceIds):Promise.resolve({data:[] as any[]}),spaceIds.length?supabase.from('sport_spaces').select('id,name').in('id',spaceIds):Promise.resolve({data:[] as any[]})]);const pm=new Map((pros||[]).map(x=>[x.id,x])),sm=new Map((services||[]).map(x=>[x.id,x])),vm=new Map((spaces||[]).map(x=>[x.id,x]));activityRows=upcoming.slice(0,5).map((r:any)=>{const p:any=pm.get(r.professional_id),s:any=sm.get(r.service_id),v:any=vm.get(r.space_id);return{id:r.id,title:s?.name||v?.name||'Reserva',subtitle:`${p?.professional_name||p?.full_name||v?.name||'Prestador'} · ${dateLabel(r.date,r.start_time)}`,status:r.status||undefined,amount:Number(r.amount||0)}});nextAction=activityRows[0]||null;metrics=[{label:'Próximos',value:upcoming.length,icon:Calendar},{label:'Compras',value:paid.length,icon:ReceiptText},{label:'Favoritos',value:favorites||0,icon:Heart},{label:'Mensagens',value:unreadMessages||0,icon:MessageSquare,hint:'não lidas'}];activityTitle='Próximas reservas';primaryLabel='Descobrir profissionais e espaços';void participations
 }
 if(role==='professional'){
  const[{count:servicesCount},{count:followers},{data:recentReservations}]=await Promise.all([supabase.from('services').select('id',{count:'exact',head:true}).eq('professional_id',entity.id),supabase.from('user_follows').select('id',{count:'exact',head:true}).eq('following_id',userId),supabase.from('reservations').select('id,user_id,service_id,date,start_time,end_time,status,amount').eq('professional_id',entity.id).order('date',{ascending:true}).order('start_time',{ascending:true}).limit(50)]);const rows=recentReservations||[],userIds=[...new Set(rows.map(r=>r.user_id).filter((id):id is string=>Boolean(id)))],serviceIds=[...new Set(rows.map(r=>r.service_id).filter((id):id is string=>Boolean(id)))];const[{data:users},{data:services}]=await Promise.all([userIds.length?supabase.from('platform_users').select('id,full_name').in('id',userIds):Promise.resolve({data:[] as any[]}),serviceIds.length?supabase.from('services').select('id,name').in('id',serviceIds):Promise.resolve({data:[] as any[]})]);const um=new Map((users||[]).map(x=>[x.id,x.full_name])),sm=new Map((services||[]).map(x=>[x.id,x.name]));const now=new Date().toISOString().slice(0,10);activityRows=rows.filter(r=>r.date>=now&&!['cancelled','completed'].includes(String(r.status))).slice(0,5).map((r:any)=>({id:r.id,title:`${um.get(r.user_id)||'Cliente'} · ${sm.get(r.service_id)||'Serviço'}`,subtitle:dateLabel(r.date,r.start_time),status:r.status||undefined,amount:Number(r.amount||0)}));nextAction=activityRows[0]||null;metrics=[{label:'Visualizações',value:entity.views_count||0,icon:Activity},{label:'Serviços',value:servicesCount||0,icon:BriefcaseBusiness},{label:'Seguidores',value:followers||0,icon:UserRound},{label:'Mensagens',value:unreadMessages||0,icon:MessageSquare,hint:'não lidas'}];activityTitle='Próximas reservas';primaryHref='/dashboard/servicos';primaryLabel='Gerir serviços'
 }
 if(role==='venue_manager'){
  const targetSpaces=selectedEntityId?entities.filter(s=>s.id===selectedEntityId):entities;const ids=targetSpaces.map(s=>s.id);const[{count:reservationCount},{count:followers},{data:rows}]=await Promise.all([ids.length?supabase.from('reservations').select('id',{count:'exact',head:true}).in('space_id',ids):Promise.resolve({count:0}),supabase.from('user_follows').select('id',{count:'exact',head:true}).eq('following_id',userId),ids.length?supabase.from('reservations').select('id,user_id,space_id,space_room_id,date,start_time,end_time,status,amount').in('space_id',ids).order('date',{ascending:true}).order('start_time',{ascending:true}).limit(100):Promise.resolve({data:[] as any[]})]);const reservations=rows||[],userIds=[...new Set(reservations.map(r=>r.user_id).filter((id):id is string=>Boolean(id)))],roomIds=[...new Set(reservations.map(r=>r.space_room_id).filter((id):id is string=>Boolean(id)))];const[{data:users},{data:rooms}]=await Promise.all([userIds.length?supabase.from('platform_users').select('id,full_name').in('id',userIds):Promise.resolve({data:[] as any[]}),roomIds.length?supabase.from('space_rooms').select('id,name').in('id',roomIds):Promise.resolve({data:[] as any[]})]);const um=new Map((users||[]).map(x=>[x.id,x.full_name])),rm=new Map((rooms||[]).map(x=>[x.id,x.name])),spaceMap=new Map(entities.map(s=>[s.id,s.name]));const today=new Date().toISOString().slice(0,10);activityRows=reservations.filter(r=>r.date>=today&&!['cancelled','completed'].includes(String(r.status))).slice(0,5).map((r:any)=>({id:r.id,title:`${um.get(r.user_id)||'Cliente'} · ${rm.get(r.space_room_id)||spaceMap.get(r.space_id)||'Espaço'}`,subtitle:`${spaceMap.get(r.space_id)||''} · ${dateLabel(r.date,r.start_time)}`,status:r.status||undefined,amount:Number(r.amount||0)}));nextAction=activityRows[0]||null;metrics=[{label:'Visualizações',value:targetSpaces.reduce((n,s)=>n+Number(s.views_count||0),0),icon:Activity},{label:'Reservas',value:reservationCount||0,icon:CalendarCheck},{label:'Espaços',value:targetSpaces.length,icon:Building2},{label:'Mensagens',value:unreadMessages||0,icon:MessageSquare,hint:'não lidas'}];activityTitle='Próximas reservas';primaryHref='/dashboard/espacos';primaryLabel='Gerir espaços';void followers
 }
 return <DashboardPage><DashboardPageHeader title={`Olá, ${displayName}`} description={role==='athlete'?'O que tens a seguir e o que precisa da tua atenção.':'Operação, agenda e ações prioritárias num único lugar.'} action={<Button asChild><Link href={primaryHref}>{primaryLabel}<ArrowRight className="ml-2 h-4 w-4"/></Link></Button>}/>
  {role==='venue_manager'&&entities.length>1&&<DashboardSection title="Espaços" description="A visão Todos agrega a operação; seleciona um espaço para detalhar."><div className="flex flex-wrap gap-2"><Button asChild variant={!selectedEntityId?'default':'outline'} size="sm"><Link href="/dashboard">Todos</Link></Button>{entities.map(s=><Button key={s.id} asChild variant={selectedEntityId===s.id?'default':'outline'} size="sm"><Link href={`/dashboard?space=${s.id}`}>{s.name}</Link></Button>)}</div></DashboardSection>}
  {nextAction&&<DashboardSection title="Próxima ação" description="A informação mais relevante vem antes dos indicadores."><div className="flex flex-col gap-4 rounded-2xl border border-primary/20 bg-primary/[0.03] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-lg font-bold">{nextAction.title}</p><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Clock3 className="h-4 w-4"/>{nextAction.subtitle}</p>{nextAction.amount!=null&&<p className="mt-1 flex items-center gap-2 text-sm font-semibold"><CircleDollarSign className="h-4 w-4"/>{nextAction.amount.toFixed(2)} €</p>}</div><div className="flex gap-2"><Button asChild variant="outline"><Link href="/dashboard/agenda">Ver agenda</Link></Button><Button asChild><Link href="/dashboard/mensagens">Mensagem</Link></Button></div></div></DashboardSection>}
  {role==='athlete'&&<div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Link href="/dashboard/agenda" className="rounded-2xl border bg-card p-4"><Calendar className="h-5 w-5 text-primary"/><p className="mt-3 font-semibold">Agenda</p></Link><Link href="/dashboard/compras" className="rounded-2xl border bg-card p-4"><ReceiptText className="h-5 w-5 text-primary"/><p className="mt-3 font-semibold">Compras</p></Link><Link href="/dashboard/mensagens" className="col-span-2 rounded-2xl border bg-card p-4 sm:col-span-1"><MessageSquare className="h-5 w-5 text-primary"/><p className="mt-3 font-semibold">Mensagens</p></Link></div>}
  <DashboardStatGrid>{metrics.map(m=><DashboardStat key={m.label} label={m.label} value={m.value} hint={m.hint} icon={<m.icon className="h-5 w-5"/>}/>)}</DashboardStatGrid>
  {role!=='athlete'&&<DashboardSection><div className="flex items-center gap-4"><div className="rounded-xl bg-amber-500/10 p-3 text-amber-600"><Star className="h-5 w-5"/></div><div><p className="font-semibold">Reputação</p><p className="text-sm text-muted-foreground">{selectedEntityId&&entity?`Rating médio: ${entity.rating_avg?Number(entity.rating_avg).toFixed(1):'Sem avaliações'} · ${entity.review_count||0} avaliações`:'Seleciona uma entidade para ver reputação individual.'}</p></div></div></DashboardSection>}
  <div className={`grid gap-5 ${hasRecentMessages?'lg:grid-cols-3':''}`}><DashboardSection title={activityTitle} description="Cliente, contexto, horário, estado e valor — sem IDs técnicos." className={hasRecentMessages?'lg:col-span-2':undefined}>{activityRows.length===0?<p className="py-8 text-center text-sm text-muted-foreground">Sem atividade futura.</p>:<div className="space-y-3">{activityRows.map(row=><Link key={row.id} href="/dashboard/agenda" className="flex items-center justify-between gap-3 rounded-xl border bg-muted/20 p-3 hover:border-primary/40"><div className="min-w-0"><p className="truncate text-sm font-medium">{row.title}</p><p className="text-xs text-muted-foreground">{row.subtitle}</p>{row.amount!=null&&<p className="mt-1 text-xs font-semibold">{row.amount.toFixed(2)} €</p>}</div>{row.status&&<Badge variant="outline">{row.status}</Badge>}</Link>)}</div>}</DashboardSection>{hasRecentMessages&&<DashboardSection title="Mensagens recentes" description="Últimas mensagens recebidas."><div className="space-y-3">{(recentMessages||[]).map(message=>{const sender=senderMap.get(message.sender_id) as any;return <div key={message.id} className="rounded-xl border p-3"><div className="mb-1 flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold">{sender?.full_name||'Utilizador'}</p>{!message.read_at&&<Badge>Novo</Badge>}</div><p className="line-clamp-2 text-xs text-muted-foreground">{message.content}</p></div>})}<Button asChild variant="outline" className="min-h-11 w-full"><Link href="/dashboard/mensagens">Abrir mensagens</Link></Button></div></DashboardSection>}</div>
 </DashboardPage>
}
