'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Crown, PackagePlus, Power, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { useModal } from '@/components/providers/modal-provider'
import { createServicePackage, deleteServicePackage, toggleServicePackage } from '@/app/dashboard/servicos/package-actions'

type Service={id:string;name:string;is_active:boolean|null}
type Package={id:string;service_id:string;name:string;sessions_count:number;price:number;validity_days:number|null;is_active:boolean}
export function ServicePackagesManager({services,initialPackages,enabled,available}:{services:Service[];initialPackages:Package[];enabled:boolean;available:boolean}){
  const{showAlert,showConfirm}=useModal();const[items,setItems]=useState(initialPackages);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[serviceId,setServiceId]=useState(services.find(s=>s.is_active!==false)?.id||'');const[name,setName]=useState('');const[sessions,setSessions]=useState('5');const[price,setPrice]=useState('');const[validity,setValidity]=useState('90')
  if(!enabled)return <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex items-start gap-3"><Crown className="mt-0.5 h-5 w-5 shrink-0 text-primary"/><div className="min-w-0"><h2 className="font-semibold">Pacotes de aulas/sessões</h2><p className="mt-1 text-sm text-muted-foreground">Venda packs pré-pagos com várias sessões. Esta funcionalidade é exclusiva do Premium.</p><Button asChild className="mt-4 min-h-11"><Link href="/dashboard/faturacao">Ver plano Premium</Link></Button></div></div></section>
  if(!available)return <section className="rounded-2xl border border-dashed p-5"><h2 className="font-semibold">Pacotes de aulas/sessões</h2><p className="mt-1 text-sm text-muted-foreground">A funcionalidade está preparada no código, mas a atualização de base de dados ainda não foi aplicada.</p></section>
  async function create(){if(!serviceId)return;setSaving(true);try{const created=await createServicePackage({serviceId,name,sessionsCount:Number(sessions),price:Number(price),validityDays:validity?Number(validity):null});setItems(prev=>[created as Package,...prev]);setOpen(false);setName('');setPrice('');showAlert('Pacote criado','O pacote já está disponível na oferta do profissional.','success')}catch(error){showAlert('Não foi possível criar o pacote',error instanceof Error?error.message:'Erro inesperado.','error')}finally{setSaving(false)}}
  async function toggle(item:Package){try{const updated=await toggleServicePackage(item.id,!item.is_active);setItems(prev=>prev.map(p=>p.id===item.id?updated as Package:p))}catch(error){showAlert('Erro',error instanceof Error?error.message:'Não foi possível alterar o pacote.','error')}}
  async function remove(item:Package){if(!(await showConfirm('Eliminar pacote',`Eliminar “${item.name}”?`,{confirmLabel:'Eliminar',destructive:true})))return;try{await deleteServicePackage(item.id);setItems(prev=>prev.filter(p=>p.id!==item.id))}catch(error){showAlert('Erro',error instanceof Error?error.message:'Não foi possível eliminar o pacote.','error')}}
  return <section className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-xl font-bold">Pacotes de sessões</h2><Badge>Premium</Badge></div><p className="mt-1 text-sm text-muted-foreground">Agrupa várias sessões num único produto com validade própria.</p></div><Button onClick={()=>setOpen(true)} disabled={!services.some(s=>s.is_active!==false)}><PackagePlus className="mr-2 h-4 w-4"/>Novo pacote</Button></div>{items.length?<div className="grid gap-3 md:grid-cols-2">{items.map(item=><article key={item.id} className={`rounded-2xl border bg-card p-4 ${!item.is_active?'opacity-65':''}`}><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{item.name}</h3><p className="mt-1 text-sm text-muted-foreground">{item.sessions_count} sessões · {item.validity_days?`${item.validity_days} dias`:'sem validade definida'}</p><p className="mt-2 text-lg font-bold">{Number(item.price).toFixed(2)} €</p></div><Badge variant={item.is_active?'success':'secondary'}>{item.is_active?'Ativo':'Inativo'}</Badge></div><div className="mt-4 flex gap-2 border-t pt-3"><Button size="sm" variant="outline" onClick={()=>void toggle(item)}><Power className="mr-1.5 h-4 w-4"/>{item.is_active?'Desativar':'Ativar'}</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={()=>void remove(item)}><Trash2 className="mr-1.5 h-4 w-4"/>Eliminar</Button></div></article>)}</div>:<div className="rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">Ainda não criaste nenhum pacote.</div>}
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Novo pacote</DialogTitle><DialogDescription>Escolhe o serviço base, número de sessões, preço total e validade.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Serviço</Label><Select value={serviceId} onValueChange={v=>setServiceId(v||'')}><SelectTrigger><SelectValue placeholder="Selecionar serviço"/></SelectTrigger><SelectContent>{services.filter(s=>s.is_active!==false).map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Nome do pacote</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Pack 10 sessões"/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Sessões</Label><Input type="number" min="2" max="100" value={sessions} onChange={e=>setSessions(e.target.value)}/></div><div className="space-y-2"><Label>Preço total (€)</Label><Input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></div></div><div className="space-y-2"><Label>Validade (dias)</Label><Input type="number" min="1" max="730" value={validity} onChange={e=>setValidity(e.target.value)} placeholder="Opcional"/></div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving||!name.trim()||!serviceId||!price} onClick={()=>void create()}>{saving?'A guardar…':'Criar pacote'}</Button></DialogFooter></DialogContent></Dialog>
  </section>
}
