import { NextResponse } from 'next/server'
import Stripe from 'stripe'
import { persistRefunds } from '@/lib/stripe/webhook/refunds/persist-refunds'
import { persistDispute } from '@/lib/stripe/webhook/disputes/persist-dispute'
import { persistTransferReversal } from '@/lib/stripe/webhook/transfers/persist-transfer-reversal'
import { persistMarketplaceTransaction } from '@/lib/stripe/webhook/marketplace/persist-marketplace-transaction'
import { persistInvoiceTransaction, syncSubscription } from '@/lib/stripe/webhook/billing/subscription-invoice'

const stripeSecretKey = process.env.STRIPE_SECRET_KEY
const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET

export async function POST(req: Request) {
  try {
    if (!stripeSecretKey || !webhookSecret) return NextResponse.json({ error: 'Webhook configuration missing' }, { status: 500 })
    const stripe = new Stripe(stripeSecretKey)
    const body = await req.text()
    const signature = req.headers.get('stripe-signature')
    if (!signature) return NextResponse.json({ error: 'Missing Stripe signature' }, { status: 400 })
    const event = stripe.webhooks.constructEvent(body, signature, webhookSecret)
    const { createClient: createSupabaseClient } = await import('@supabase/supabase-js')
    const db = createSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!) as any
    const { data: processedEvent } = await db.from('stripe_webhook_events').select('id').eq('event_id', event.id).maybeSingle()
    if (processedEvent) return NextResponse.json({ received: true })
    const recordEvent = async (extra: Record<string, unknown> = {}) => { const { error } = await db.from('stripe_webhook_events').upsert({ event_id:event.id,event_type:event.type,payload:event as any,...extra },{onConflict:'event_id',ignoreDuplicates:true}); if(error) throw error }

    if(event.type==='checkout.session.completed'||event.type==='checkout.session.async_payment_succeeded'){
      const session=event.data.object as Stripe.Checkout.Session
      if(event.type==='checkout.session.completed'&&session.payment_status!=='paid'){await recordEvent({financial_metadata:{checkout_session_id:session.id,payment_status:session.payment_status,fulfillment_deferred:true}});return NextResponse.json({received:true,deferred:true})}
      if(session.mode==='subscription'&&session.subscription){const subscriptionId=typeof session.subscription==='string'?session.subscription:session.subscription.id;await syncSubscription(db,await stripe.subscriptions.retrieve(subscriptionId));await recordEvent();return NextResponse.json({received:true})}
      const packagePurchaseId=session.metadata?.service_package_purchase_id
      if(packagePurchaseId){const {data:purchase,error:purchaseError}=await db.from('service_package_purchases').select('id,user_id,package_id,sessions_total,price_paid,status').eq('id',packagePurchaseId).maybeSingle();if(purchaseError||!purchase)return NextResponse.json({error:'Package purchase not found'},{status:404});const paidAmount=Number(session.amount_total||0)/100;if(Number(purchase.price_paid)!==paidAmount)return NextResponse.json({error:'Package amount mismatch'},{status:400});if(purchase.status==='pending'){const {data:packageDefinition,error:packageError}=await db.from('service_packages').select('validity_days').eq('id',purchase.package_id).maybeSingle();if(packageError||!packageDefinition)throw new Error('Package definition not found while activating purchase');const purchasedAt=new Date(),validityDays=packageDefinition.validity_days==null?null:Number(packageDefinition.validity_days),expiresAt=validityDays&&validityDays>0?new Date(purchasedAt.getTime()+validityDays*86400000).toISOString():null,paymentIntentId=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id;const {error}=await db.from('service_package_purchases').update({status:'active',sessions_remaining:Number(purchase.sessions_total),purchased_at:purchasedAt.toISOString(),expires_at:expiresAt,stripe_session_id:session.id,stripe_payment_intent_id:paymentIntentId||null,updated_at:purchasedAt.toISOString()}).eq('id',packagePurchaseId).eq('status','pending');if(error)throw error}const settlement=await persistMarketplaceTransaction(db,stripe,session,purchase.user_id,'service_package',packagePurchaseId);await recordEvent({service_package_purchase_id:packagePurchaseId,stripe_payment_intent_id:settlement.paymentIntentId});return NextResponse.json({received:true})}
      const eventParticipantId=session.metadata?.event_participant_id
      if(eventParticipantId){const {data:participant}=await db.from('event_participants').select('id,event_id,user_id,amount,payment_status,status').eq('id',eventParticipantId).maybeSingle();if(!participant)return NextResponse.json({error:'Event participant not found'},{status:404});const paidAmount=Number(session.amount_total||0)/100;if(Number(participant.amount)!==paidAmount)return NextResponse.json({error:'Event amount mismatch'},{status:400});if(participant.payment_status!=='paid'){const {error}=await db.from('event_participants').update({status:'confirmed',payment_status:'paid',updated_at:new Date().toISOString()}).eq('id',eventParticipantId);if(error)throw error}const settlement=await persistMarketplaceTransaction(db,stripe,session,participant.user_id,'event',eventParticipantId);await recordEvent({event_participant_id:eventParticipantId,stripe_payment_intent_id:settlement.paymentIntentId});return NextResponse.json({received:true})}
      const reservationId=session.metadata?.reservation_id
      if(reservationId){const {data:reservation}=await db.from('reservations').select('id,user_id,amount,payment_status,service_id,space_id').eq('id',reservationId).maybeSingle();if(!reservation)return NextResponse.json({error:'Reservation not found'},{status:404});const paidAmount=Number(session.amount_total||0)/100;if(Number(reservation.amount)!==paidAmount)return NextResponse.json({error:'Amount mismatch'},{status:400});if(reservation.payment_status!=='paid'){const {error}=await db.from('reservations').update({status:'paid',payment_status:'paid'}).eq('id',reservationId);if(error)throw error}const sourceType=reservation.space_id?'space_reservation':'service_reservation',settlement=await persistMarketplaceTransaction(db,stripe,session,reservation.user_id,sourceType,reservationId);await recordEvent({reservation_id:reservationId,stripe_payment_intent_id:settlement.paymentIntentId});return NextResponse.json({received:true})}
    }

    if(event.type==='checkout.session.expired'||event.type==='checkout.session.async_payment_failed'){const session=event.data.object as Stripe.Checkout.Session,packagePurchaseId=session.metadata?.service_package_purchase_id||null,eventParticipantId=session.metadata?.event_participant_id||null,reservationId=session.metadata?.reservation_id||null;if(packagePurchaseId){const {error}=await db.from('service_package_purchases').delete().eq('id',packagePurchaseId).eq('status','pending').eq('stripe_session_id',session.id);if(error)throw error}if(eventParticipantId){const {error}=await db.from('event_participants').delete().eq('id',eventParticipantId).eq('status','pending').eq('payment_status','pending');if(error)throw error}if(reservationId){const {error}=await db.from('reservations').delete().eq('id',reservationId).eq('status','pending').eq('payment_status','pending').eq('stripe_session_id',session.id);if(error)throw error}await recordEvent({service_package_purchase_id:packagePurchaseId,event_participant_id:eventParticipantId,reservation_id:reservationId,financial_metadata:{checkout_session_id:session.id,cleanup_reason:event.type}});return NextResponse.json({received:true})}
    if(event.type==='charge.refunded'){const charge=event.data.object as Stripe.Charge;await persistRefunds(db,charge);await recordEvent({stripe_payment_intent_id:typeof charge.payment_intent==='string'?charge.payment_intent:charge.payment_intent?.id||null});return NextResponse.json({received:true})}
    if(event.type==='charge.dispute.created'||event.type==='charge.dispute.updated'||event.type==='charge.dispute.closed'){const dispute=event.data.object as Stripe.Dispute;await persistDispute(db,dispute);await recordEvent({stripe_payment_intent_id:typeof dispute.payment_intent==='string'?dispute.payment_intent:dispute.payment_intent?.id||null});return NextResponse.json({received:true})}
    if(event.type==='transfer.reversed'){const transfer=event.data.object as Stripe.Transfer;await persistTransferReversal(db,transfer);await recordEvent();return NextResponse.json({received:true})}
    if(event.type==='transfer.created'||event.type==='transfer.updated'){const transfer=event.data.object as Stripe.Transfer,destination=typeof transfer.destination==='string'?transfer.destination:transfer.destination?.id||null;const {error}=await db.from('transactions').update({stripe_connected_account_id:destination||undefined,financial_metadata:{transfer_status_event:event.type,transfer_id:transfer.id}}).eq('stripe_transfer_id',transfer.id);if(error)throw error;await recordEvent();return NextResponse.json({received:true})}
    if(event.type==='payout.created'||event.type==='payout.updated'||event.type==='payout.paid'||event.type==='payout.failed'||event.type==='payout.canceled'){const payout=event.data.object as Stripe.Payout;await recordEvent({stripe_connected_account_id:typeof event.account==='string'?event.account:null,financial_metadata:{payout_id:payout.id,payout_status:payout.status,payout_amount:payout.amount,payout_currency:payout.currency}} as any);return NextResponse.json({received:true})}
    if(event.type==='customer.subscription.created'||event.type==='customer.subscription.updated'||event.type==='customer.subscription.deleted'){const subscription=event.data.object as Stripe.Subscription;await syncSubscription(db,subscription,event.type==='customer.subscription.deleted');await recordEvent();return NextResponse.json({received:true})}
    if(event.type==='invoice.paid'){await persistInvoiceTransaction(db,event.data.object as Stripe.Invoice,'completed');await recordEvent();return NextResponse.json({received:true})}
    if(event.type==='invoice.payment_failed'){const invoice=event.data.object as Stripe.Invoice,customerId=typeof invoice.customer==='string'?invoice.customer:invoice.customer?.id;if(customerId){const {error}=await db.from('user_subscriptions').update({status:'past_due',updated_at:new Date().toISOString()}).eq('stripe_customer_id',customerId);if(error)throw error}await persistInvoiceTransaction(db,invoice,'failed');await recordEvent();return NextResponse.json({received:true})}
    await recordEvent();return NextResponse.json({received:true})
  } catch(err:any){console.error('Webhook error:',err.message);return NextResponse.json({error:'Webhook Error'},{status:400})}
}
