'use server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { resolveSessionAccess } from '@/lib/auth/access'
import { writeAdminAudit } from '@/lib/admin/audit'
const MAX_NAME_LENGTH=180,MAX_ADDRESS_LENGTH=500
type SpaceFilter='all'|'active'|'pending'|'managed'|'unmanaged'
async function requireAdmin(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão administrativa inválida.');const access=await resolveSessionAccess(supabase,user);if(!access?.canAccessAdmin)throw new Error('Acesso administrativo necessário.');return{user,admin:createAdminClient()}}
function text(value:unknown,max:number){return String(value||'').trim().slice(0,max)}
async function categories(admin:ReturnType<typeof createAdminClient>,ids:string[]){const unique=[...new Set(ids.filter(id=>/^[0-9a-f-]{36}$/i.test(id)))].slice(0,5);if(!unique.length)throw new Error('Seleciona pelo menos uma modalidade.');const{data,error}=await admin.from('categories').select('id').in('id',unique);if(error||(data||[]).length!==unique.length)throw new Error('Uma ou mais modalidades são inválidas.');return unique}
async function owner(admin:ReturnType<typeof createAdminClient>,id:string|null|undefined){if(!id)return null;if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Gestor inválido.');const{data}=await admin.from('platform_users').select('id,type').eq('id',id).maybeSingle();if(!data||data.type!=='venue_manager')throw new Error('O gestor selecionado não tem role de gestor de espaço.');return data.id}
export async function getAdminSpaceFormOptionsAction(){const{admin}=await requireAdmin();const[c,m]=await Promise.all([admin.from('categories').select('id,name,slug,emoji,parent_id').order('name'),admin.from('platform_users').select('id,full_name,type').eq('type','venue_manager').order('full_name').limit(500)]);if(c.error||m.error)throw new Error('Não foi possível carregar as opções do formulário.');return{categories:c.data||[],managers:m.data||[]}}
export async function getAdminSpacesAction(input?:{page?:number;pageSize?:number;search?:string;filter?:SpaceFilter}){const{admin}=await requireAdmin();const page=Math.max(1,Math.floor(input?.page||1)),pageSize=Math.min(50,Math.max(5,Math.floor(input?.pageSize||20))),search=String(input?.search||'').trim().replace(/[,%]/g,'').slice(0,100),filter:SpaceFilter=['active','pending','managed','unmanaged'].includes(String(input?.filter))?input!.filter as SpaceFilter:'all',from=(page-1)*pageSize,to=from+pageSize-1;let query=admin.from('sport_spaces').select('id,name,slug,address,status,is_verified,owner_user_id,created_at,rating_avg,review_count,logo_url',{count:'exact'}).order('name',{ascending:true});if(search)query=query.or(`name.ilike.%${search}%,address.ilike.%${search}%`);if(filter==='active')query=query.eq('status','active').eq('is_verified',true);if(filter==='pending')query=query.or('status.neq.active,is_verified.eq.false');if(filter==='managed')query=query.not('owner_user_id','is',null);if(filter==='unmanaged')query=query.is('owner_user_id',null);const{data,count,error}=await query.range(from,to);if(error)throw new Error(`Não foi possível carregar os espaços: ${error.message}`);const rows=data||[],ownerIds=[...new Set(rows.map(row=>row.owner_user_id).filter((value):value is string=>Boolean(value)))];const ownersResult=ownerIds.length?await admin.from('platform_users').select('id,full_name,type').in('id',ownerIds):{data:[] as Array<{id:string;full_name:string|null;type:string|null}>,error:null};if(ownersResult.error)throw new Error(`Não foi possível carregar os gestores: ${ownersResult.error.message}`);const ownerMap=new Map((ownersResult.data||[]).map(o=>[o.id,o]));const enriched=await Promise.all(rows.map(async row=>{if(!row.owner_user_id)return{...row,owner:null};const profile=ownerMap.get(row.owner_user_id)||null,auth=await admin.auth.admin.getUserById(row.owner_user_id);if(auth.error)throw new Error(`Não foi possível validar o gestor de ${row.name}: ${auth.error.message}`);return{...row,owner:profile?{...profile,email:auth.data.user?.email||null}:{id:row.owner_user_id,full_name:null,email:auth.data.user?.email||null}}}));return{items:enriched,total:count??0,page,pageSize,totalPages:Math.max(1,Math.ceil((count??0)/pageSize))}}
export async function getAdminSpaceStatsAction(){const{admin}=await requireAdmin();const[totalResult,activeResult,unmanagedResult]=await Promise.all([admin.from('sport_spaces').select('id',{count:'exact',head:true}),admin.from('sport_spaces').select('id',{count:'exact',head:true}).eq('status','active').eq('is_verified',true),admin.from('sport_spaces').select('id',{count:'exact',head:true}).is('owner_user_id',null)]);const failures=[totalResult.error&&`total: ${totalResult.error.message}`,activeResult.error&&`ativos: ${activeResult.error.message}`,unmanagedResult.error&&`sem gestor: ${unmanagedResult.error.message}`].filter(Boolean) as string[];if(failures.length)throw new Error(`Não foi possível calcular os indicadores. ${failures.join(' · ')}`);const total=totalResult.count??0,active=activeResult.count??0;return{total,active,pending:Math.max(0,total-active),unmanaged:unmanagedResult.count??0}}
export async function setAdminSpaceStatusAction(spaceId:string,active:boolean){const id=String(spaceId||'').trim();if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Identificador inválido.');const{user,admin}=await requireAdmin();const{data,error}=await admin.from('sport_spaces').update({status:active?'active':'pending',is_verified:active}).eq('id',id).select('id,status,is_verified').single();if(error)throw new Error(`Não foi possível alterar o estado: ${error.message}`);await writeAdminAudit(admin as any,{action:'UPDATE',tableName:'sport_spaces',userEmail:user.email||'admin',message:`Estado do espaço ${id} alterado para ${data.status}`,data:{space_id:id,status:data.status}});return data}
type SpaceInput={name:string;address:string;description?:string|null;phone?:string|null;email?:string|null;website?:string|null;amenities?:string[];category_ids?:string[];owner_user_id?:string|null}
export async function createAdminSpaceAction(input:SpaceInput){const{user,admin}=await requireAdmin();const name=text(input.name,MAX_NAME_LENGTH),address=text(input.address,MAX_ADDRESS_LENGTH);if(name.length<2||address.length<5)throw new Error('Nome e localização válidos são obrigatórios.');const categoryIds=await categories(admin,input.category_ids||[]),ownerId=await owner(admin,input.owner_user_id);const slugBase=name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)+/g,'')||'espaco',slug=`${slugBase}-${crypto.randomUUID().slice(0,8)}`;const{data,error}=await admin.from('sport_spaces').insert({name,address,description:text(input.description,5000)||null,phone:text(input.phone,40)||null,email:text(input.email,254)||null,website:text(input.website,500)||null,amenities:(input.amenities||[]).map(v=>text(v,80)).filter(Boolean).slice(0,30),slug,status:'pending',is_verified:false,owner_user_id:ownerId,created_by:null}).select().single();if(error)throw new Error(`Não foi possível criar o espaço: ${error.message}`);const{error:categoryError}=await admin.from('space_categories').insert(categoryIds.map(category_id=>({space_id:data.id,category_id})));if(categoryError){await admin.from('sport_spaces').delete().eq('id',data.id);throw new Error(`Não foi possível associar modalidades: ${categoryError.message}`)}await writeAdminAudit(admin as any,{action:'INSERT',tableName:'sport_spaces',userEmail:user.email||'admin',message:`Espaço ${data.id} criado administrativamente`,data:{space_id:data.id,owner_user_id:ownerId}});return data}
export async function updateAdminSpaceAction(spaceId:string,input:SpaceInput){if(!/^[0-9a-f-]{36}$/i.test(spaceId))throw new Error('Espaço inválido.');const{user,admin}=await requireAdmin();const name=text(input.name,MAX_NAME_LENGTH),address=text(input.address,MAX_ADDRESS_LENGTH);if(name.length<2||address.length<5)throw new Error('Nome e localização válidos são obrigatórios.');const categoryIds=await categories(admin,input.category_ids||[]),ownerId=await owner(admin,input.owner_user_id);const{data,error}=await admin.from('sport_spaces').update({name,address,description:text(input.description,5000)||null,phone:text(input.phone,40)||null,email:text(input.email,254)||null,website:text(input.website,500)||null,amenities:(input.amenities||[]).map(v=>text(v,80)).filter(Boolean).slice(0,30),owner_user_id:ownerId}).eq('id',spaceId).select('id').single();if(error)throw new Error(`Não foi possível atualizar o espaço: ${error.message}`);const{data:previous}=await admin.from('space_categories').select('category_id').eq('space_id',spaceId);const{error:deleteError}=await admin.from('space_categories').delete().eq('space_id',spaceId);if(deleteError)throw new Error(deleteError.message);const{error:insertError}=await admin.from('space_categories').insert(categoryIds.map(category_id=>({space_id:spaceId,category_id})));if(insertError){if(previous?.length)await admin.from('space_categories').insert(previous.map(row=>({space_id:spaceId,category_id:row.category_id})));throw new Error(insertError.message)}await writeAdminAudit(admin as any,{action:'UPDATE',tableName:'sport_spaces',userEmail:user.email||'admin',message:`Espaço ${spaceId} atualizado administrativamente`,data:{space_id:spaceId,owner_user_id:ownerId}});return data}
