'use client'
import { useEffect, useState, type Dispatch, type ReactNode, type SetStateAction } from 'react'
import { Loader2, Plus } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { createAdminSpaceAction, getAdminSpaceFormOptionsAction, updateAdminSpaceAction } from './actions'
import { useModal } from '@/components/providers/modal-provider'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { TaxonomyCombobox, type TaxonomyOption } from '@/components/taxonomy-combobox'
type Manager={id:string;full_name:string|null;type:string|null}
type FormState={name:string;description:string;address:string;phone:string;email:string;website:string;amenities:string;owner_user_id:string}
const empty:FormState={name:'',description:'',address:'',phone:'',email:'',website:'',amenities:'',owner_user_id:''}
function payload(form:FormState,categories:string[]){return{name:form.name,address:form.address,description:form.description||null,phone:form.phone||null,email:form.email||null,website:form.website||null,amenities:form.amenities.split(',').map(v=>v.trim()).filter(Boolean),category_ids:categories,owner_user_id:form.owner_user_id||null}}
export function AdminSpaceCreateDialog(){const router=useRouter(),{showAlert}=useModal();const[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[loading,setLoading]=useState(false),[form,setForm]=useState(empty),[categories,setCategories]=useState<TaxonomyOption[]>([]),[selected,setSelected]=useState<string[]>([]),[managers,setManagers]=useState<Manager[]>([]);useEffect(()=>{if(!open||categories.length)return;setLoading(true);void getAdminSpaceFormOptionsAction().then(result=>{setCategories(result.categories.map(row=>({id:row.id,name:row.name,slug:row.slug,emoji:row.emoji,parent_id:row.parent_id})));setManagers(result.managers)}).catch(error=>showAlert('Erro',error instanceof Error?error.message:'Não foi possível carregar opções.','error')).finally(()=>setLoading(false))},[open,categories.length,showAlert]);const submit=async()=>{if(form.name.trim().length<2||form.address.trim().length<5||!selected.length)return showAlert('Dados em falta','Nome, morada e pelo menos uma modalidade são obrigatórios.','error');setSaving(true);try{await createAdminSpaceAction(payload(form,selected));setOpen(false);setForm(empty);setSelected([]);router.refresh();showAlert('Espaço criado','O espaço foi criado como pendente. Pode ficar sem gestor e ser administrado pela equipa.','success')}catch(error){showAlert('Erro',error instanceof Error?error.message:'Não foi possível criar o espaço.','error')}finally{setSaving(false)}};return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button><Plus className="mr-2 h-4 w-4"/>Adicionar espaço</Button>}/><DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Novo espaço</DialogTitle><DialogDescription>Mesmos dados essenciais do onboarding. O gestor é opcional.</DialogDescription></DialogHeader>{loading?<div className="flex justify-center p-10"><Loader2 className="h-6 w-6 animate-spin"/></div>:<SpaceFields form={form} setForm={setForm} categories={categories} selected={selected} setSelected={setSelected} managers={managers}/>}<Button onClick={submit} disabled={saving||loading}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Criar como pendente</Button></DialogContent></Dialog>}
export function AdminSpaceEditor({spaceId,initial,categories,selectedCategoryIds,managers}:{spaceId:string;initial:FormState;categories:TaxonomyOption[];selectedCategoryIds:string[];managers:Manager[]}){const router=useRouter(),{showAlert}=useModal();const[form,setForm]=useState(initial),[selected,setSelected]=useState(selectedCategoryIds),[saving,setSaving]=useState(false);const submit=async()=>{setSaving(true);try{await updateAdminSpaceAction(spaceId,payload(form,selected));router.refresh();showAlert('Espaço atualizado','Dados, modalidades e gestor foram guardados.','success')}catch(error){showAlert('Erro',error instanceof Error?error.message:'Não foi possível atualizar o espaço.','error')}finally{setSaving(false)}};return <div className="space-y-5"><SpaceFields form={form} setForm={setForm} categories={categories} selected={selected} setSelected={setSelected} managers={managers}/><Button onClick={submit} disabled={saving}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Guardar alterações</Button></div>}
function SpaceFields({form,setForm,categories,selected,setSelected,managers}:{form:FormState;setForm:Dispatch<SetStateAction<FormState>>;categories:TaxonomyOption[];selected:string[];setSelected:(value:string[])=>void;managers:Manager[]}){return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome *"><Input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></Field><Field label="Gestor"><select value={form.owner_user_id} onChange={e=>setForm(v=>({...v,owner_user_id:e.target.value}))} className="min-h-11 w-full rounded-lg border border-input bg-background px-3"><option value="">Sem gestor — gerir pelo Admin</option>{managers.map(manager=><option key={manager.id} value={manager.id}>{manager.full_name||manager.id}</option>)}</select></Field></div><Field label="Descrição"><Textarea rows={4} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></Field><Field label="Modalidades *"><TaxonomyCombobox options={categories} value={selected} multiple maxSelected={5} onChange={value=>setSelected(Array.isArray(value)?value:[])} placeholder="Pesquisar modalidades"/></Field><Field label="Morada *"><Input value={form.address} onChange={e=>setForm(v=>({...v,address:e.target.value}))}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Telefone"><Input value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/></Field><Field label="Email"><Input type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/></Field></div><Field label="Website"><Input value={form.website} onChange={e=>setForm(v=>({...v,website:e.target.value}))}/></Field><Field label="Comodidades"><Input value={form.amenities} onChange={e=>setForm(v=>({...v,amenities:e.target.value}))} placeholder="Balneários, estacionamento, cafetaria…"/><p className="text-xs text-muted-foreground">Separadas por vírgulas.</p></Field></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block space-y-2"><Label>{label}</Label>{children}</label>}
