import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CalendarDays, CreditCard, ReceiptText, ShoppingBag } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { resolveSessionAccess } from '@/lib/auth/access'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DashboardPage, DashboardPageHeader, DashboardSection, DashboardStat, DashboardStatGrid } from '@/components/patterns/dashboard-page'

function money(value:number|null|undefined){return new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(value||0))}
function statusLabel(value:string|null|undefined){const v=String(value||'pending');return v==='paid'?'Pago':v==='confirmed'?'Confirmado':v==='completed'?'Concluído':v==='cancelled'?'Cancelado':v==='refunded'?'Reembolsado':v==='failed'?'Falhou':'Pendente'}
function badgeVariant(value:string|null|undefined):'default'|'secondary'|'destructive'|'outline'{const v=String(value||'');return ['paid','confirmed','completed'].includes(v)?'default':['cancelled','failed'].includes(v)?'destructive':'secondary'}

export default async function PurchasesPage(){
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login?redirect=/dashboard/compras')
  const access=await resolveSessionAccess(supabase,user);if(!access||access.role!=='athlete')redirect('/dashboard/faturacao')
  const admin=createAdminClient()
  const [{data:reservations},{data:participants},{data:transactions}]=await Promise.all([
    admin.from('reservations').select('id,user_id,service_id,professional_id,space_id,date,start_time,end_time,amount,status,payment_status,created_at').eq('user_id',user.id).order('date',{ascending:false}),
    admin.from('event_participants').select('id,event_id,status,payment_status,created_at').eq('user_id',user.id).order('created_at',{ascending:false}),
    admin.from('transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100),
  ])
  const serviceIds=[...new Set((reservations||[]).map(r=>r.service_id).filter((x):x is string=>Boolean(x)))],proIds=[...new Set((reservations||[]).map(r=>r.professional_id).filter((x):x is string=>Boolean(x)))],spaceIds=[...new Set((reservations||[]).map(r=>r.space_id).filter((x):x is string=>Boolean(x)))],eventIds=[...new Set((participants||[]).map(p=>p.event_id))]
  const [services,pros,spaces,events]=await Promise.all([
    serviceIds.length?admin.from('services').select('id,name').in('id',serviceIds):Promise.resolve({data:[]}),
    proIds.length?admin.from('professionals').select('id,full_name,professional_name,public_slug').in('id',proIds):Promise.resolve({data:[]}),
    spaceIds.length?admin.from('sport_spaces').select('id,name,slug').in('id',spaceIds):Promise.resolve({data:[]}),
    eventIds.length?admin.from('events').select('id,title,start_date,price_min').in('id',eventIds):Promise.resolve({data:[]}),
  ])
  const serviceMap=new Map((services.data||[]).map(x=>[x.id,x])),proMap=new Map((pros.data||[]).map(x=>[x.id,x])),spaceMap=new Map((spaces.data||[]).map(x=>[x.id,x])),eventMap=new Map((events.data||[]).map(x=>[x.id,x]))
  const purchases=[...(reservations||[]).map(r=>{const service=r.service_id?serviceMap.get(r.service_id):null,pro=r.professional_id?proMap.get(r.professional_id):null,space=r.space_id?spaceMap.get(r.space_id):null;return{id:`r-${r.id}`,kind:service?'Serviço':'Espaço',title:service?.name||space?.name||'Reserva',provider:pro?.professional_name||pro?.full_name||space?.name||'',date:r.date,time:`${String(r.start_time).slice(0,5)}–${String(r.end_time).slice(0,5)}`,amount:Number(r.amount||0),status:r.status,paymentStatus:r.payment_status,href:pro?`/profissionais/${pro.public_slug||pro.id}`:space?`/espacos/${space.slug||space.id}`:'#'}}),...(participants||[]).map(p=>{const event=eventMap.get(p.event_id);return{id:`e-${p.id}`,kind:'Evento',title:event?.title||'Evento',provider:'',date:event?.start_date?new Date(event.start_date).toISOString().slice(0,10):String(p.created_at).slice(0,10),time:event?.start_date?new Date(event.start_date).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'}):'',amount:Number(event?.price_min||0),status:p.status,paymentStatus:p.payment_status,href:`/eventos/${p.event_id}`}})].sort((a,b)=>b.date.localeCompare(a.date))
  const totalPaid=purchases.filter(p=>['paid','confirmed','completed'].includes(String(p.paymentStatus))||['paid','completed'].includes(String(p.status))).reduce((sum,p)=>sum+p.amount,0),upcoming=purchases.filter(p=>p.date>=new Date().toISOString().slice(0,10)&&!['cancelled','refunded'].includes(String(p.status))).length,pending=purchases.filter(p=>['pending'].includes(String(p.paymentStatus))||['pending'].includes(String(p.status))).length
  return <DashboardPage><DashboardPageHeader title="Faturação e compras" description="Serviços, alugueres e eventos pagos através da FIND4SPORT, com estado financeiro e operacional." action={<Button asChild variant="outline"><Link href="/dashboard/agenda"><CalendarDays className="mr-2 h-4 w-4"/>Ver agenda</Link></Button>}/><DashboardStatGrid><DashboardStat label="Total comprado" value={money(totalPaid)} icon={<CreditCard className="h-5 w-5"/>}/><DashboardStat label="Compras" value={purchases.length} icon={<ShoppingBag className="h-5 w-5"/>}/><DashboardStat label="Próximos" value={upcoming} icon={<CalendarDays className="h-5 w-5"/>}/><DashboardStat label="Pendentes" value={pending} icon={<ReceiptText className="h-5 w-5"/>}/></DashboardStatGrid><DashboardSection title="Histórico de compras" description="O estado do pagamento é separado do estado da prestação do serviço.">{purchases.length===0?<div className="rounded-xl border border-dashed p-8 text-center"><p className="text-sm text-muted-foreground">Ainda não tens serviços, espaços ou eventos comprados.</p><Button asChild className="mt-4"><Link href="/pesquisa">Explorar</Link></Button></div>:<div className="divide-y rounded-2xl border">{purchases.map(p=><Link key={p.id} href={p.href} className="grid gap-3 p-4 transition hover:bg-muted/30 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{p.kind}</Badge><h3 className="truncate font-semibold">{p.title}</h3></div>{p.provider&&<p className="mt-1 text-sm text-muted-foreground">{p.provider}</p>}<p className="mt-1 text-xs text-muted-foreground">{new Date(`${p.date}T12:00:00`).toLocaleDateString('pt-PT')} {p.time&&`· ${p.time}`}</p></div><div className="flex items-center justify-between gap-3 sm:flex-col sm:items-end"><strong>{money(p.amount)}</strong><div className="flex gap-1.5"><Badge variant={badgeVariant(p.paymentStatus)}>Pagamento: {statusLabel(p.paymentStatus)}</Badge><Badge variant={badgeVariant(p.status)}>{statusLabel(p.status)}</Badge></div></div></Link>)}</div>}</DashboardSection>{transactions&&transactions.length>0&&<DashboardSection title="Movimentos financeiros" description="Registos financeiros associados à tua conta."><div className="divide-y rounded-2xl border">{transactions.slice(0,20).map((tx:any)=><div key={tx.id} className="flex items-center justify-between gap-3 p-4 text-sm"><div className="min-w-0"><p className="truncate font-medium">{tx.description||tx.type||'Movimento'}</p><p className="text-xs text-muted-foreground">{new Date(tx.created_at).toLocaleDateString('pt-PT')} · {statusLabel(tx.status)}</p></div><strong>{money(tx.amount)}</strong></div>)}</div></DashboardSection>}</DashboardPage>
}
