import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Activity, Calendar, Edit, ExternalLink, MapPin, Plus, Search, Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { resolveSessionAccess } from '@/lib/auth/access'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { DashboardEmptyState, DashboardPage, DashboardPageHeader, DashboardSection } from '@/components/patterns/dashboard-page'

const PAGE_SIZE=20
function href(page:number,q:string,status:string){const p=new URLSearchParams();if(page>1)p.set('page',String(page));if(q)p.set('q',q);if(status!=='all')p.set('status',status);return `/dashboard/eventos${p.toString()?`?${p}`:''}`}
const statusLabel:Record<string,string>={draft:'Rascunho',pending:'Pendente',published:'Publicado',cancelled:'Cancelado',completed:'Concluído',confirmed:'Confirmado',attended:'Participou'}

export default async function DashboardEventosPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login?redirect=/dashboard/eventos');const access=await resolveSessionAccess(supabase,user);if(!access)redirect('/dashboard')
  const params=await searchParams;const page=Math.max(1,Number(Array.isArray(params.page)?params.page[0]:params.page)||1);const q=String(Array.isArray(params.q)?params.q[0]:params.q||'').trim().replace(/[,%]/g,'').slice(0,100);const status=String(Array.isArray(params.status)?params.status[0]:params.status||'all');const isCreator=['professional','venue_manager'].includes(access.role)
  const from=(page-1)*PAGE_SIZE
  let rows:any[]=[];let total=0
  if(isCreator){let query:any=supabase.from('events').select('id,title,description,start_date,end_date,address,capacity,status,category_id,image_url,created_at,slug',{count:'exact'}).eq('created_by',user.id).order('start_date',{ascending:false});if(q)query=query.or(`title.ilike.%${q}%,address.ilike.%${q}%`);if(status!=='all')query=query.eq('status',status);const result=await query.range(from,from+PAGE_SIZE-1);if(result.error)throw new Error(`Não foi possível carregar eventos: ${result.error.message}`);rows=result.data||[];total=result.count||0}
  else {let query:any=supabase.from('event_participants').select('id,status,created_at,event:events(id,title,start_date,address,image_url,status,slug)',{count:'exact'}).eq('user_id',user.id).order('created_at',{ascending:false});if(status!=='all')query=query.eq('status',status);const result=await query.range(from,from+PAGE_SIZE-1);if(result.error)throw new Error(`Não foi possível carregar inscrições: ${result.error.message}`);rows=(result.data||[]).filter((en:any)=>!q||`${en.event?.title||''} ${en.event?.address||''}`.toLowerCase().includes(q.toLowerCase()));total=result.count||0}
  const totalPages=Math.max(1,Math.ceil(total/PAGE_SIZE))

  return <DashboardPage><DashboardPageHeader title={isCreator?'Gestão de Eventos':'Os meus eventos'} description={isCreator?'Eventos criados pela tua conta, independentemente do número de espaços que geres.':'Eventos em que estás inscrito.'} action={isCreator?<div className="flex flex-col gap-2 sm:flex-row"><Button asChild variant="outline"><Link href="/dashboard/agenda">Agenda</Link></Button><Button asChild><Link href="/dashboard/eventos/criar"><Plus className="mr-2 h-4 w-4"/>Criar evento</Link></Button></div>:undefined}/><DashboardSection title={isCreator?'Eventos criados':'Inscrições'} description="Pesquisa, filtro de estado e paginação."><form method="get" className="mb-4 grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_200px_auto]"><label className="relative min-w-0"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input name="q" defaultValue={q} placeholder="Título ou localização" className="min-h-11 w-full pl-10"/></label><select name="status" defaultValue={status} className="min-h-11 rounded-lg border border-input bg-background px-3"><option value="all">Todos os estados</option>{(isCreator?['draft','pending','published','cancelled','completed']:['pending','confirmed','cancelled','attended']).map(v=><option key={v} value={v}>{statusLabel[v]||v}</option>)}</select><Button type="submit">Filtrar</Button></form>
    {rows.length===0?<DashboardEmptyState icon={isCreator?<Calendar className="h-10 w-10"/>:<Activity className="h-10 w-10"/>} title={isCreator?'Sem eventos':'Sem inscrições'} description="Não existem resultados para estes filtros." action={isCreator?<Button asChild><Link href="/dashboard/eventos/criar">Criar evento</Link></Button>:<Button asChild><Link href="/eventos">Explorar eventos</Link></Button>}/>:<div className="grid min-w-0 gap-3">{rows.map((row:any)=>{const event=isCreator?row:row.event;return <article key={row.id} className="flex min-w-0 flex-col gap-4 overflow-hidden rounded-2xl border bg-card p-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 gap-3">{event?.image_url&&<img src={event.image_url} alt="" className="h-20 w-24 shrink-0 rounded-xl object-cover"/>}<div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="break-words font-semibold">{event?.title||'Evento indisponível'}</h3><Badge variant="outline">{statusLabel[isCreator?row.status:row.status]||row.status}</Badge></div><p className="mt-2 flex min-w-0 items-center gap-1.5 text-sm text-muted-foreground"><Calendar className="h-4 w-4 shrink-0"/>{event?.start_date?new Date(event.start_date).toLocaleString('pt-PT'):'Data indisponível'}</p>{event?.address&&<p className="mt-1 flex min-w-0 items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="h-4 w-4 shrink-0"/><span className="truncate">{event.address}</span></p>}{isCreator&&row.capacity&&<p className="mt-1 flex items-center gap-1.5 text-sm text-muted-foreground"><Users className="h-4 w-4"/>{row.capacity} lugares</p>}</div></div><div className="grid grid-cols-2 gap-2 sm:flex"><Button asChild variant="outline"><Link href={`/eventos/${event?.slug||event?.id}`}><ExternalLink className="mr-2 h-4 w-4"/>Ver</Link></Button>{isCreator&&<Button asChild variant="outline"><Link href={`/dashboard/eventos/${row.id}/editar`}><Edit className="mr-2 h-4 w-4"/>Editar</Link></Button>}</div></article>})}</div>}
    {total>0&&<div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-sm text-muted-foreground">{from+1}–{Math.min(from+PAGE_SIZE,total)} de {total}</span><div className="flex items-center gap-2"><Button asChild variant="outline" size="sm" className={page<=1?'pointer-events-none opacity-50':''}><Link href={href(page-1,q,status)}>Anterior</Link></Button><span className="text-sm">{page}/{totalPages}</span><Button asChild variant="outline" size="sm" className={page>=totalPages?'pointer-events-none opacity-50':''}><Link href={href(page+1,q,status)}>Seguinte</Link></Button></div></div>}
  </DashboardSection></DashboardPage>
}
