import Link from 'next/link'
import { redirect } from 'next/navigation'
import { CreditCard, DollarSign, TrendingUp, Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { resolveSessionAccess } from '@/lib/auth/access'
import type { Tables } from '@/lib/supabase-types'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { DashboardEmptyState, DashboardPage, DashboardPageHeader, DashboardSection, DashboardStat, DashboardStatGrid } from '@/components/patterns/dashboard-page'

const PAGE_SIZE=20
type SubscriptionStatus=NonNullable<Tables<'user_subscriptions'>['status']>;type SubscriptionStatusFilter='all'|SubscriptionStatus
const ACTIVE_SUBSCRIPTION_STATUSES:SubscriptionStatus[]=['active','trialing']
const money=(v:number)=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v);const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:0};const firstParam=(v:string|string[]|undefined,f:string)=>Array.isArray(v)?v[0]||f:v||f
function parseSubscriptionStatus(v:string):SubscriptionStatusFilter{return ['active','canceled','past_due','trialing','incomplete','incomplete_expired','unpaid','paused'].includes(v)?v as SubscriptionStatus:'all'}
function pageHref(p:{subPage?:number;txPage?:number;subStatus?:string;txStatus?:string;txType?:string}){const q=new URLSearchParams();if((p.subPage||1)>1)q.set('subPage',String(p.subPage));if((p.txPage||1)>1)q.set('txPage',String(p.txPage));if(p.subStatus&&p.subStatus!=='all')q.set('subStatus',p.subStatus);if(p.txStatus&&p.txStatus!=='all')q.set('txStatus',p.txStatus);if(p.txType&&p.txType!=='all')q.set('txType',p.txType);return `/admin/faturacao${q.toString()?`?${q}`:''}`}

export default async function AdminBillingPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/admin/login');const access=await resolveSessionAccess(supabase,user);if(!access?.canAccessAdmin)redirect('/admin/login?error=unauthorized')
 const params=await searchParams,subPage=Math.max(1,Number(firstParam(params.subPage,'1'))||1),txPage=Math.max(1,Number(firstParam(params.txPage,'1'))||1),subStatus=parseSubscriptionStatus(firstParam(params.subStatus,'all')),txStatus=firstParam(params.txStatus,'all'),txType=firstParam(params.txType,'all'),dateFrom=firstParam(params.dateFrom,''),dateTo=firstParam(params.dateTo,''),minAmount=Math.max(0,Number(firstParam(params.minAmount,'0'))||0),maxAmount=Math.max(0,Number(firstParam(params.maxAmount,'0'))||0),reference=firstParam(params.reference,'').trim(),admin=createAdminClient()
 let subQuery=admin.from('user_subscriptions').select('id,user_id,tier,status,created_at,current_period_end,user:platform_users(id,full_name,type),plan:subscription_plans(id,name,monthly_price,audience)',{count:'exact'}).order('created_at',{ascending:false});if(subStatus!=='all')subQuery=subQuery.eq('status',subStatus)
 let txQuery=admin.from('transactions').select('*',{count:'exact'}).order('created_at',{ascending:false});if(txStatus!=='all')txQuery=txQuery.eq('status',txStatus);if(txType!=='all')txQuery=txQuery.eq('type',txType);if(dateFrom)txQuery=txQuery.gte('created_at',dateFrom);if(dateTo)txQuery=txQuery.lt('created_at',new Date(new Date(dateTo).getTime()+86400000).toISOString());if(minAmount)txQuery=txQuery.gte('amount',minAmount);if(maxAmount)txQuery=txQuery.lte('amount',maxAmount);if(reference)txQuery=txQuery.or(`id.eq.${reference},stripe_payment_intent_id.eq.${reference},stripe_charge_id.eq.${reference}`)
 const [sr,tr,ar,cr]=await Promise.all([subQuery.range((subPage-1)*PAGE_SIZE,subPage*PAGE_SIZE-1),txQuery.range((txPage-1)*PAGE_SIZE,txPage*PAGE_SIZE-1),admin.from('user_subscriptions').select('id,status,plan:subscription_plans(monthly_price)').in('status',ACTIVE_SUBSCRIPTION_STATUSES),admin.from('transactions').select('*').eq('status','completed')]);if(sr.error)throw new Error(sr.error.message);if(tr.error)throw new Error(tr.error.message);if(ar.error)throw new Error(ar.error.message);if(cr.error)throw new Error(cr.error.message)
 const subscriptions=sr.data||[],transactions=tr.data||[],active=ar.data||[],completed=cr.data||[],userIds=[...new Set(transactions.map(t=>t.user_id).filter((id):id is string=>Boolean(id)))],users=new Map<string,Pick<Tables<'platform_users'>,'full_name'|'type'>>()
 if(userIds.length){const {data,error}=await admin.from('platform_users').select('id,full_name,type').in('id',userIds);if(error)throw new Error(error.message);for(const p of data||[])users.set(p.id,{full_name:p.full_name,type:p.type})}
 const mrr=active.reduce((s,x)=>s+num(x.plan?.monthly_price),0),market=completed.filter(x=>['service_reservation_payment','space_reservation_payment','event_payment','service_package_payment'].includes(String(x.type))),volume=completed.reduce((s,x)=>s+num(x.gross_amount??x.amount),0),commissions=market.reduce((s,x)=>s+num(x.platform_commission_amount),0),stripeFees=market.reduce((s,x)=>s+num(x.stripe_processing_fee_amount),0),platformNet=market.reduce((s,x)=>s+num(x.platform_net_amount),0),subTotal=sr.count||0,txTotal=tr.count||0,subPages=Math.max(1,Math.ceil(subTotal/PAGE_SIZE)),txPages=Math.max(1,Math.ceil(txTotal/PAGE_SIZE))
 return <DashboardPage><DashboardPageHeader title="Faturação" description="Consola financeira auditável: subscrições, pagamentos, comissões, Stripe, settlements, refunds e disputas."/><DashboardStatGrid><DashboardStat label="MRR" value={money(mrr)} icon={<TrendingUp className="h-5 w-5"/>}/><DashboardStat label="Volume bruto" value={money(volume)} icon={<CreditCard className="h-5 w-5"/>}/><DashboardStat label="Comissões marketplace" value={money(commissions)} icon={<DollarSign className="h-5 w-5"/>}/><DashboardStat label="Líquido plataforma" value={money(platformNet)} icon={<TrendingUp className="h-5 w-5"/>}/></DashboardStatGrid><BillingAdvancedFilters values={{dateFrom,dateTo,minAmount,maxAmount,reference,txStatus,txType}}/>
 {market.length>0&&<DashboardSection title="Resumo marketplace" description="Valores derivados das transações concluídas."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Comissão bruta',commissions],['Fees Stripe',stripeFees],['Líquido plataforma',platformNet]].map(([l,v])=><div key={String(l)} className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">{l}</p><p className="mt-1 text-lg font-bold">{money(Number(v))}</p></div>)}<div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Operações marketplace</p><p className="mt-1 text-lg font-bold">{market.length}</p></div></div></DashboardSection>}
 <div className="grid min-w-0 gap-6 xl:grid-cols-2"><DashboardSection title="Subscrições" description="Filtro de estado e paginação independente."><form method="get" className="mb-4 grid gap-2 sm:grid-cols-[1fr_auto]"><input type="hidden" name="txPage" value={txPage}/><input type="hidden" name="txStatus" value={txStatus}/><input type="hidden" name="txType" value={txType}/><select name="subStatus" defaultValue={subStatus} className="min-h-11 rounded-lg border border-input bg-background px-3"><option value="all">Todos os estados</option>{['active','trialing','past_due','canceled','incomplete','unpaid'].map(v=><option key={v}>{v}</option>)}</select><Button type="submit" variant="outline">Filtrar</Button></form>{subscriptions.length===0?<DashboardEmptyState icon={<Users className="h-10 w-10"/>} title="Sem subscrições" description="Nenhum resultado para este filtro."/>:<div className="space-y-3">{subscriptions.map(s=><article key={s.id} className="flex gap-3 rounded-xl border p-3 sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">{s.user?.full_name||'Utilizador'}</p><p className="text-xs text-muted-foreground">{s.plan?.name||s.tier||'Sem plano'} · {s.user?.type||'perfil'}</p></div><div className="flex gap-2"><Badge variant="outline">{s.status||'sem estado'}</Badge>{s.plan?.monthly_price!=null&&<span className="text-sm font-semibold">{money(num(s.plan.monthly_price))}/mês</span>}</div></article>)}</div>}{subTotal>0&&<Pager current={subPage} pages={subPages} total={subTotal} prev={pageHref({subPage:subPage-1,txPage,subStatus,txStatus,txType})} next={pageHref({subPage:subPage+1,txPage,subStatus,txStatus,txType})}/>}</DashboardSection>
 <DashboardSection title="Transações" description="Abra uma operação para auditar origem, intervenientes, decomposição financeira e IDs Stripe."><form method="get" className="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="subPage" value={subPage}/><input type="hidden" name="subStatus" value={subStatus}/><select name="txStatus" defaultValue={txStatus} className="min-h-11 rounded-lg border border-input bg-background px-3"><option value="all">Todos os estados</option>{['completed','pending','failed'].map(v=><option key={v}>{v}</option>)}</select><select name="txType" defaultValue={txType} className="min-h-11 rounded-lg border border-input bg-background px-3"><option value="all">Todos os tipos</option>{['subscription_payment','service_reservation_payment','space_reservation_payment','event_payment','service_package_payment','refund','dispute','transfer_reversal'].map(v=><option key={v}>{v}</option>)}</select><Button type="submit" variant="outline">Filtrar</Button></form>{transactions.length===0?<DashboardEmptyState icon={<CreditCard className="h-10 w-10"/>} title="Sem transações" description="Nenhum movimento para estes filtros."/>:<div className="space-y-3">{transactions.map(t=>{const u=t.user_id?users.get(t.user_id):undefined;return <article key={t.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{t.type||'Transação'}</p><p className="text-xs text-muted-foreground">{u?.full_name||'Sistema'} · {new Date(t.created_at).toLocaleString('pt-PT')}</p></div><div className="text-right"><p className="text-sm font-bold">{money(num(t.gross_amount??t.amount))}</p><Badge variant="outline">{t.status||'sem estado'}</Badge></div></div><div className="mt-3 flex justify-end border-t pt-3"><Button asChild size="sm" variant="outline"><Link href={`/admin/faturacao/transacoes/${t.id}`}>Abrir transação</Link></Button></div></article>})}</div>}{txTotal>0&&<Pager current={txPage} pages={txPages} total={txTotal} prev={pageHref({subPage,txPage:txPage-1,subStatus,txStatus,txType})} next={pageHref({subPage,txPage:txPage+1,subStatus,txStatus,txType})}/>}</DashboardSection></div></DashboardPage>
}
function Pager({current,pages,total,prev,next}:{current:number;pages:number;total:number;prev:string;next:string}){return <div className="mt-4 flex items-center justify-between border-t pt-3"><span className="text-xs text-muted-foreground">{total} resultados</span><div className="flex items-center gap-2"><Button asChild variant="outline" size="sm" className={current<=1?'pointer-events-none opacity-50':''}><Link href={prev}>Anterior</Link></Button><span className="text-xs">{current}/{pages}</span><Button asChild variant="outline" size="sm" className={current>=pages?'pointer-events-none opacity-50':''}><Link href={next}>Seguinte</Link></Button></div></div>}
function BillingAdvancedFilters({values}:{values:{dateFrom:string;dateTo:string;minAmount:number;maxAmount:number;reference:string;txStatus:string;txType:string}}){return <DashboardSection title="Pesquisa financeira" description="Cruze período, montante e referência Stripe/Find4Sport."><form method="get" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="txStatus" value={values.txStatus}/><input type="hidden" name="txType" value={values.txType}/><FilterInput label="Desde" name="dateFrom" type="date" value={values.dateFrom}/><FilterInput label="Até" name="dateTo" type="date" value={values.dateTo}/><FilterInput label="Montante mínimo" name="minAmount" type="number" value={values.minAmount||''}/><FilterInput label="Montante máximo" name="maxAmount" type="number" value={values.maxAmount||''}/><FilterInput label="ID / referência" name="reference" value={values.reference}/><div className="flex gap-2 sm:col-span-2 lg:col-span-5"><Button type="submit">Aplicar filtros</Button><Button asChild type="button" variant="outline"><Link href="/admin/faturacao">Limpar</Link></Button></div></form></DashboardSection>}
function FilterInput({label,name,type='text',value}:{label:string;name:string;type?:string;value:string|number}){return <label className="text-xs font-medium">{label}<input name={name} type={type} defaultValue={value} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} className="mt-1 min-h-11 w-full rounded-lg border bg-background px-3 text-sm"/></label>}
