import Link from 'next/link'
import { Globe, Lock, MapPin, Navigation, Plus, Search, Users } from 'lucide-react'
import { cookies } from 'next/headers'
import { createAdminClient } from '@/lib/supabase/admin'
import { DiscoveryEmptyState, DiscoveryPage } from '@/components/patterns/discovery-page'
import { DiscoveryPagination } from '@/components/patterns/discovery-pagination'
import { Button } from '@/components/ui/button'
import { parseGeoCookie } from '@/lib/geo'
import type { Category } from '@/lib/types'

const PAGE_SIZE=24
function branchIds(categories:Category[],selectedId:string){const ids=new Set<string>([selectedId]);let changed=true;while(changed){changed=false;for(const c of categories)if(c.parent_id&&ids.has(c.parent_id)&&!ids.has(c.id)){ids.add(c.id);changed=true}}return[...ids]}
function href(filters:Record<string,string|undefined>,updates:Record<string,string|undefined|null>){const p=new URLSearchParams();Object.entries({...filters,...updates}).forEach(([k,v])=>{if(!v||(k==='sort'&&v==='newest')||(k==='page'&&v==='1'))return;p.set(k,v)});return p.size?`/comunidades?${p}`:'/comunidades'}
const scopeLabel:Record<string,string>={online:'Online',local:'Local',regional:'Regional',national:'Nacional'}

export default async function CommunitiesPage({searchParams}:{searchParams:Promise<{category?:string;q?:string;sort?:string;page?:string}>}){
 const admin=createAdminClient();const cookieStore=await cookies();const userLocation=parseGeoCookie(cookieStore.get('f4s_geo')?.value);const filters=await searchParams;const sort=filters.sort||'newest';const page=Math.max(1,Number.parseInt(filters.page||'1',10)||1)
 const[{data:categoryRows},{data:categoryLinks}]=await Promise.all([admin.from('categories').select('*').order('name'),admin.from('community_categories').select('category_id')]);const categories=(categoryRows||[]) as Category[];const selected=filters.category?categories.find(c=>c.slug===filters.category||c.id===filters.category):undefined;const categoryIds=selected?branchIds(categories,selected.id):null
 const{data,error}=await (admin as any).rpc('discover_communities',{p_lat:userLocation?.latitude??null,p_lng:userLocation?.longitude??null,p_category_ids:categoryIds,p_q:filters.q||null,p_sort:sort,p_offset:(page-1)*PAGE_SIZE,p_limit:PAGE_SIZE});if(error)throw new Error(`Não foi possível carregar comunidades: ${error.message}`)
 const rows=(data||[]) as Array<{item:any;total_count:number|string}>;const communities=rows.map(r=>r.item);const total=Number(rows[0]?.total_count||0);const counts=new Map<string,number>();for(const l of categoryLinks||[])counts.set(l.category_id,(counts.get(l.category_id)||0)+1);const topCategories=categories.filter(c=>counts.has(c.id)).sort((a,b)=>(counts.get(b.id)||0)-(counts.get(a.id)||0)).slice(0,10);const record=filters as Record<string,string|undefined>
 const search=<form action="/comunidades" method="get" className="relative w-full max-w-3xl"><Search className="pointer-events-none absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground"/><input name="q" defaultValue={filters.q||''} placeholder="Pesquisar comunidades..." className="min-h-12 w-full rounded-xl border bg-background pl-10 pr-4 text-base outline-none focus:border-primary"/>{filters.category&&<input type="hidden" name="category" value={filters.category}/>}</form>
 return <DiscoveryPage title="Comunidades" description="Junta-te a grupos desportivos online ou com localização própria." countLabel={`${total} ${total===1?'comunidade encontrada':'comunidades encontradas'}`} search={search} action={<Button asChild className="min-h-11 w-full sm:w-auto"><Link href="/comunidades/criar"><Plus className="mr-2 h-4 w-4"/>Criar comunidade</Link></Button>} categories={[{label:'Todas',href:href(record,{category:null,page:null}),active:!selected},...topCategories.map(c=>({label:c.name,href:href(record,{category:c.slug||c.id,page:null}),active:selected?.id===c.id}))]} sorts={[{label:'Recentes',href:href(record,{sort:'newest',page:null}),active:sort==='newest'},...(userLocation?[{label:'Mais próximas',href:href(record,{sort:'distance',page:null}),active:sort==='distance'}]:[]),{label:'Mais membros',href:href(record,{sort:'members',page:null}),active:sort==='members'},{label:'A–Z',href:href(record,{sort:'name',page:null}),active:sort==='name'}]} clearHref={filters.q||filters.category||sort!=='newest'?'/comunidades':undefined}>
  {communities.length?<><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{communities.map((c:any)=>{const distance=c.distanceKm==null?null:c.distanceKm<1?`${Math.round(c.distanceKm*1000)} m`:`${Number(c.distanceKm).toFixed(1)} km`;const primaryCategory=c.categories?.[0]?.name||c.sport_category||'Desporto';return <Link key={c.id} href={`/comunidades/${c.slug||c.id}`} className="group flex min-w-0 flex-col overflow-hidden rounded-2xl border bg-card transition hover:border-primary/40 hover:shadow-md"><div className="relative aspect-[16/9] overflow-hidden bg-muted">{c.cover_url?<img src={c.cover_url} alt={c.name} className="h-full w-full object-cover transition duration-300 group-hover:scale-[1.03]"/>:<div className="flex h-full items-center justify-center bg-primary/10 text-3xl font-bold text-primary">{c.name?.charAt(0)?.toUpperCase()||'C'}</div>}<span className="absolute left-2 top-2 max-w-[70%] truncate rounded-full bg-black/55 px-2 py-1 text-[10px] font-semibold text-white">{primaryCategory}</span>{distance&&<span className="absolute bottom-2 right-2 rounded-full bg-background/95 px-2 py-1 text-[10px] font-semibold shadow"><Navigation className="mr-1 inline h-3 w-3 text-primary"/>{distance}</span>}</div><div className="flex flex-1 flex-col p-3"><h2 className="line-clamp-1 text-sm font-bold group-hover:text-primary sm:text-base">{c.name}</h2><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{c.description||'Comunidade desportiva na Find4Sport.'}</p>{c.address&&<p className="mt-2 flex items-center gap-1 text-[10px] text-muted-foreground"><MapPin className="h-3 w-3 shrink-0"/><span className="truncate">{c.address}</span></p>}<div className="mt-auto flex items-center justify-between gap-2 pt-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1"><Users className="h-3.5 w-3.5"/>{c.memberCount||0}</span><span>{scopeLabel[c.location_scope]||'Online'}</span><span className="flex items-center gap-1">{c.is_private?<Lock className="h-3.5 w-3.5"/>:<Globe className="h-3.5 w-3.5"/>}{c.is_private?'Privada':'Pública'}</span></div></div></Link>})}</div><DiscoveryPagination page={page} pageSize={PAGE_SIZE} total={total} href={n=>href(record,{page:String(n)})}/></>:<DiscoveryEmptyState title="Nenhuma comunidade encontrada" description="Experimenta remover filtros ou cria uma nova comunidade." clearHref="/comunidades"/>}
 </DiscoveryPage>
}
