import { NextResponse } from 'next/server'
import Stripe from 'stripe'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { marketplaceLineItems, marketplacePaymentIntentData, resolveMarketplacePaymentQuote } from '@/lib/billing/marketplace-payment'

function toMinutes(value:string){const[h,m]=value.split(':').map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:NaN}
function addMinutes(value:string,duration:number){const start=toMinutes(value),total=start+duration;if(!Number.isFinite(start)||total>=1440)return null;return`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}
function normalizeConfiguredOrigin(value:string|undefined){const configured=value?.trim();if(!configured)return null;try{return new URL(/^https?:\/\//i.test(configured)?configured:`https://${configured}`).origin}catch{return null}}
function getBaseUrl(request:Request){const configured=normalizeConfiguredOrigin(process.env.NEXT_PUBLIC_SITE_URL);if(configured)return configured;const deployment=normalizeConfiguredOrigin(process.env.VERCEL_URL);if(deployment)return deployment;return new URL(request.url).origin}

export async function POST(request:Request){
 try{
  const secret=process.env.STRIPE_SECRET_KEY;if(!secret)return NextResponse.json({error:'Stripe não está configurado.'},{status:503});const stripe=new Stripe(secret);const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Autenticação necessária.'},{status:401});const admin=createAdminClient();const body=await request.json().catch(()=>({}));const baseUrl=getBaseUrl(request)
  if(body.eventId){
    const eventId=String(body.eventId),ticketTypeId=body.ticketTypeId?String(body.ticketTypeId):null;const{data:event,error:eventError}=await admin.from('events').select('id,title,status,capacity,start_date,created_by').eq('id',eventId).maybeSingle();if(eventError||!event)return NextResponse.json({error:'Evento não encontrado.'},{status:404});if(event.status!=='published'||new Date(event.start_date).getTime()<=Date.now())return NextResponse.json({error:'Este evento já não aceita inscrições.'},{status:409});if(!event.created_by)return NextResponse.json({error:'O evento não tem organizador de pagamento válido.'},{status:409});if(event.created_by===user.id)return NextResponse.json({error:'Não podes comprar uma inscrição no teu próprio evento.'},{status:400})
    let ticketQuery=admin.from('event_ticket_types').select('id,name,description,price,capacity,is_active').eq('event_id',eventId).eq('is_active',true);if(ticketTypeId)ticketQuery=ticketQuery.eq('id',ticketTypeId);else ticketQuery=ticketQuery.order('sort_order',{ascending:true}).limit(1);const{data:ticket,error:ticketError}=await ticketQuery.maybeSingle();if(ticketError||!ticket)return NextResponse.json({error:'Tipo de bilhete indisponível.'},{status:409});const baseAmountCents=Math.round(Number(ticket.price||0)*100);if(!(baseAmountCents>0))return NextResponse.json({error:'Este bilhete não requer pagamento online.'},{status:400})
    const{data:existing}=await admin.from('event_participants').select('id,status').eq('event_id',eventId).eq('user_id',user.id).maybeSingle();if(existing)return NextResponse.json({error:'Já estás inscrito neste evento.'},{status:409})
    if(event.capacity&&Number(event.capacity)>0){const{count}=await admin.from('event_participants').select('id',{count:'exact',head:true}).eq('event_id',eventId).in('status',['confirmed','paid','pending']);if((count||0)>=Number(event.capacity))return NextResponse.json({error:'Evento esgotado.'},{status:409})}
    if(ticket.capacity&&Number(ticket.capacity)>0){const{count}=await admin.from('event_participants').select('id',{count:'exact',head:true}).eq('ticket_type_id',ticket.id).in('status',['confirmed','paid','pending']);if((count||0)>=Number(ticket.capacity))return NextResponse.json({error:'Este tipo de bilhete está esgotado.'},{status:409})}
    const quote=await resolveMarketplacePaymentQuote(event.created_by,baseAmountCents);const{data:participant,error:participantError}=await admin.from('event_participants').insert({event_id:eventId,user_id:user.id,status:'pending',payment_status:'pending',ticket_type_id:ticket.id,amount:Number(ticket.price)}).select('id').single();if(participantError||!participant)return NextResponse.json({error:'Não foi possível iniciar a inscrição.'},{status:500})
    try{const metadata={event_participant_id:participant.id,event_id:eventId,ticket_type_id:ticket.id,transaction_type:'event',buyer_user_id:user.id};const session=await stripe.checkout.sessions.create({mode:'payment',line_items:marketplaceLineItems(quote,`Evento: ${event.title}`,`Bilhete: ${ticket.name}`),payment_intent_data:marketplacePaymentIntentData(quote,metadata),success_url:new URL('/dashboard/agenda?event=success&session_id={CHECKOUT_SESSION_ID}',baseUrl).toString(),cancel_url:new URL(`/eventos/${eventId}?event=cancelled`,baseUrl).toString(),client_reference_id:participant.id,metadata},{idempotencyKey:`event-checkout:${participant.id}`});if(!session.url)throw new Error('Stripe não devolveu URL de checkout.');return NextResponse.json({url:session.url})}catch(error){await admin.from('event_participants').delete().eq('id',participant.id).eq('status','pending').eq('payment_status','pending');throw error}
  }
  const serviceId=body.serviceId?String(body.serviceId):null,professionalId=body.professionalId?String(body.professionalId):null,spaceId=body.spaceId?String(body.spaceId):null,spaceRoomId=body.spaceRoomId?String(body.spaceRoomId):null,date=String(body.date||''),startTime=String(body.startTime||'').slice(0,5);if(!date||!startTime||(!serviceId&&!spaceRoomId))return NextResponse.json({error:'Dados da reserva incompletos.'},{status:400});const bookingDate=new Date(`${date}T12:00:00`),today=new Date();today.setHours(0,0,0,0);if(Number.isNaN(bookingDate.getTime())||bookingDate<today)return NextResponse.json({error:'Data da reserva inválida.'},{status:400});if(!Number.isFinite(toMinutes(startTime)))return NextResponse.json({error:'Hora de início inválida.'},{status:400})
  let baseAmountCents=0,title='Reserva',durationMinutes=60,resolvedProfessionalId:string|null=null,resolvedSpaceId:string|null=null,resolvedRoomId:string|null=null,providerUserId:string|null=null,destinationAccountId:string|null=null,cancelReturn='/'
  if(serviceId){const{data:service,error}=await admin.from('services').select('id,name,price,professional_id,duration_minutes,is_active').eq('id',serviceId).maybeSingle();if(error||!service||!service.is_active)return NextResponse.json({error:'Serviço indisponível.'},{status:404});const{data:provider}=await admin.from('professionals').select('user_id,stripe_account_id,status').eq('id',service.professional_id).maybeSingle();if(!provider||provider.status!=='active')return NextResponse.json({error:'O profissional não está disponível.'},{status:409});if(provider.user_id===user.id)return NextResponse.json({error:'Não podes reservar o teu próprio serviço.'},{status:400});if(professionalId&&service.professional_id!==professionalId)return NextResponse.json({error:'Serviço inválido para este profissional.'},{status:400});baseAmountCents=Math.round(Number(service.price||0)*100);title=service.name||'Serviço';durationMinutes=Math.max(1,Number(service.duration_minutes||60));resolvedProfessionalId=service.professional_id;providerUserId=provider.user_id;destinationAccountId=provider.stripe_account_id||null;cancelReturn=`/profissionais/${service.professional_id}`
  }else{const{data:room,error}=await admin.from('space_rooms').select('id,name,space_id,price_per_hour,is_active').eq('id',spaceRoomId!).maybeSingle();if(error||!room||!room.is_active)return NextResponse.json({error:'Sala/campo indisponível.'},{status:404});const{data:space}=await admin.from('sport_spaces').select('id,owner_user_id,stripe_account_id,status').eq('id',room.space_id).maybeSingle();if(!space||space.status!=='active')return NextResponse.json({error:'O espaço não está disponível.'},{status:409});if(space.owner_user_id===user.id)return NextResponse.json({error:'Não podes reservar o teu próprio espaço.'},{status:400});if(spaceId&&room.space_id!==spaceId)return NextResponse.json({error:'Sala/campo inválido para este espaço.'},{status:400});baseAmountCents=Math.round(Number(room.price_per_hour||0)*100);title=room.name||'Sala/Campo';resolvedSpaceId=room.space_id;resolvedRoomId=room.id;providerUserId=space.owner_user_id;destinationAccountId=space.stripe_account_id||null;cancelReturn=`/espacos/${room.space_id}`}
  if(!(baseAmountCents>0))return NextResponse.json({error:'Esta reserva não requer pagamento online.'},{status:400});if(!providerUserId)return NextResponse.json({error:'Prestador de pagamento inválido.'},{status:409});const quote=await resolveMarketplacePaymentQuote(providerUserId,baseAmountCents,destinationAccountId),endTime=addMinutes(startTime,durationMinutes);if(!endTime)return NextResponse.json({error:'Intervalo horário inválido.'},{status:400});const dayOfWeek=bookingDate.getDay()
  if(resolvedProfessionalId){const{data:slots,error}=await admin.from('professional_availability').select('start_time,end_time').eq('professional_id',resolvedProfessionalId).eq('day_of_week',dayOfWeek).eq('is_active',true);if(error)return NextResponse.json({error:'Não foi possível validar disponibilidade.'},{status:500});if(!(slots||[]).some(s=>startTime>=String(s.start_time).slice(0,5)&&endTime<=String(s.end_time).slice(0,5)))return NextResponse.json({error:'O horário está fora da disponibilidade do profissional.'},{status:409})}
  if(resolvedRoomId){const{data:slots,error}=await admin.from('space_room_availability').select('start_time,end_time').eq('room_id',resolvedRoomId).eq('day_of_week',dayOfWeek).eq('is_active',true);if(error)return NextResponse.json({error:'Não foi possível validar disponibilidade da sala/campo.'},{status:500});if(!(slots||[]).some(s=>startTime>=String(s.start_time).slice(0,5)&&endTime<=String(s.end_time).slice(0,5)))return NextResponse.json({error:'O horário está fora da disponibilidade da sala/campo.'},{status:409})}
  let overlap=admin.from('reservations').select('id').eq('date',date).in('status',['pending','paid','confirmed']).lt('start_time',endTime).gt('end_time',startTime);if(resolvedProfessionalId)overlap=overlap.eq('professional_id',resolvedProfessionalId);if(resolvedRoomId)overlap=overlap.eq('space_room_id',resolvedRoomId);const overlapResult=await overlap.limit(1);if(overlapResult.error)return NextResponse.json({error:`Não foi possível validar conflitos: ${overlapResult.error.message}`},{status:500});if(overlapResult.data?.length)return NextResponse.json({error:'Este horário já não está disponível.'},{status:409})
  const{data:reservation,error:reservationError}=await admin.from('reservations').insert({user_id:user.id,professional_id:resolvedProfessionalId,service_id:serviceId,space_id:resolvedSpaceId,space_room_id:resolvedRoomId,date,start_time:startTime,end_time:endTime,amount:quote.totalAmountCents/100,status:'pending',payment_status:'pending'}).select('id').single();if(reservationError||!reservation)return NextResponse.json({error:reservationError?.message?`Não foi possível criar a reserva: ${reservationError.message}`:'Não foi possível criar a reserva.'},{status:500})
  try{const transactionType=resolvedRoomId?'space_reservation':'service_reservation';const metadata={reservation_id:reservation.id,transaction_type:transactionType,buyer_user_id:user.id,...(resolvedRoomId?{space_room_id:resolvedRoomId}:{})};const session=await stripe.checkout.sessions.create({mode:'payment',line_items:marketplaceLineItems(quote,`Reserva: ${title}`,`Data: ${bookingDate.toLocaleDateString('pt-PT')} · ${startTime}–${endTime}`),payment_intent_data:marketplacePaymentIntentData(quote,metadata),success_url:new URL('/dashboard/agenda?booking=success&session_id={CHECKOUT_SESSION_ID}',baseUrl).toString(),cancel_url:new URL(`${cancelReturn}?booking=cancelled`,baseUrl).toString(),client_reference_id:reservation.id,metadata},{idempotencyKey:`reservation-checkout:${reservation.id}`});if(!session.url)throw new Error('Stripe não devolveu URL de checkout.');const{error:linkError}=await admin.from('reservations').update({stripe_session_id:session.id}).eq('id',reservation.id);if(linkError){if(session.status==='open')await stripe.checkout.sessions.expire(session.id).catch(()=>undefined);await admin.from('reservations').delete().eq('id',reservation.id).eq('status','pending');throw new Error('Não foi possível associar o checkout à reserva.')}return NextResponse.json({url:session.url})}catch(error){await admin.from('reservations').delete().eq('id',reservation.id).eq('status','pending').eq('payment_status','pending');throw error}
 }catch(error){console.error('Booking checkout error:',error);return NextResponse.json({error:error instanceof Error?error.message:'Erro ao iniciar pagamento.'},{status:500})}
}
