import Link from 'next/link'
import { redirect } from 'next/navigation'
import { BadgeCheck, Building2, ChevronLeft, ChevronRight, Dumbbell, Search, UserRound, Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { getFollowersList, getFollowingList } from '@/app/actions/follow'
import { FollowButton } from '@/components/follow-button'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { DashboardEmptyState, DashboardPage, DashboardPageHeader, DashboardSection, DashboardStat, DashboardStatGrid } from '@/components/patterns/dashboard-page'

const PAGE_SIZE=20
function RoleAvatar({item}:{item:any}){const rounded=item.type==='venue_manager'?'rounded-xl':'rounded-full';return <div className={`flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden border bg-muted ${rounded}`}>{item.avatar?<img src={item.avatar} alt={item.name} className="h-full w-full object-cover"/>:item.type==='venue_manager'?<Building2 className="h-5 w-5 text-primary"/>:item.type==='professional'?<Dumbbell className="h-5 w-5 text-primary"/>:<UserRound className="h-5 w-5 text-primary"/>}</div>}
function roleLabel(role:string){return role==='professional'?'Profissional':role==='venue_manager'?'Gestor de espaço':'Atleta'}
function href(fp:number,rp:number,q:string,type:string){const p=new URLSearchParams();if(fp>1)p.set('followingPage',String(fp));if(rp>1)p.set('followersPage',String(rp));if(q)p.set('q',q);if(type!=='all')p.set('type',type);return `/dashboard/seguidores${p.toString()?`?${p}`:''}`}

export default async function NetworkPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login?redirect=/dashboard/seguidores')
  const params=await searchParams;const get=(k:string,f:string)=>String(Array.isArray(params[k])?params[k]![0]:params[k]||f);const q=get('q','').trim().toLowerCase();const rawType=get('type','all');const type=['athlete','professional','venue_manager'].includes(rawType)?rawType:'all';const followingPage=Math.max(1,Number(get('followingPage','1'))||1);const followersPage=Math.max(1,Number(get('followersPage','1'))||1)
  const [followingResult,followersResult]=await Promise.all([getFollowingList(user.id),getFollowersList(user.id)]);const following=followingResult.list||[];const followers=followersResult.list||[];const mutualCount=following.filter((item:any)=>followers.some((f:any)=>f.userId===item.userId)).length
  const apply=(items:any[])=>items.filter(item=>(type==='all'||item.type===type)&&(!q||`${item.name} ${roleLabel(item.type)}`.toLowerCase().includes(q)));const filteredFollowing=apply(following);const filteredFollowers=apply(followers);const fPages=Math.max(1,Math.ceil(filteredFollowing.length/PAGE_SIZE));const rPages=Math.max(1,Math.ceil(filteredFollowers.length/PAGE_SIZE));const fPage=Math.min(followingPage,fPages);const rPage=Math.min(followersPage,rPages);const visibleFollowing=filteredFollowing.slice((fPage-1)*PAGE_SIZE,fPage*PAGE_SIZE);const visibleFollowers=filteredFollowers.slice((rPage-1)*PAGE_SIZE,rPage*PAGE_SIZE)
  const list=(items:any[],followingMode:boolean)=>items.length===0?<DashboardEmptyState icon={<Users className="h-10 w-10"/>} title={followingMode?'Sem resultados a seguir':'Sem seguidores encontrados'} description="Ajusta a pesquisa ou os filtros."/>:<div className="divide-y divide-border">{items.map((item:any)=><article key={item.userId} className="flex min-w-0 items-center justify-between gap-3 py-3"><Link href={item.href} className="flex min-w-0 flex-1 items-center gap-3"><RoleAvatar item={item}/><div className="min-w-0"><div className="flex items-center gap-1.5"><p className="truncate text-sm font-semibold">{item.name}</p>{item.isVerified&&<BadgeCheck className="h-4 w-4 shrink-0 text-primary"/>}</div><p className="text-xs text-muted-foreground">{roleLabel(item.type)}</p></div></Link>{item.userId!==user.id&&<FollowButton targetUserId={item.userId} initialIsFollowing={followingMode?true:Boolean(item.isFollowedByMe)} variant="outline"/>}</article>)}</div>
  return <DashboardPage><DashboardPageHeader title="Rede" description="Pessoas e entidades que segue, e utilizadores que seguem o seu perfil."/><DashboardStatGrid><DashboardStat label="A seguir" value={following.length} icon={<UserRound className="h-5 w-5"/>}/><DashboardStat label="Seguidores" value={followers.length} icon={<Users className="h-5 w-5"/>}/><DashboardStat label="Mútuos" value={mutualCount} icon={<Users className="h-5 w-5"/>}/><DashboardStat label="Rede total" value={new Set([...following.map((i:any)=>i.userId),...followers.map((i:any)=>i.userId)]).size} icon={<Users className="h-5 w-5"/>}/></DashboardStatGrid><form method="get" className="grid min-w-0 gap-2 rounded-2xl border bg-card p-4 sm:grid-cols-[minmax(0,1fr)_200px_auto]"><label className="relative min-w-0"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input name="q" defaultValue={q} placeholder="Pesquisar rede" className="min-h-11 w-full pl-10"/></label><select name="type" defaultValue={type} className="min-h-11 rounded-lg border border-input bg-background px-3"><option value="all">Todos os tipos</option><option value="athlete">Atletas</option><option value="professional">Profissionais</option><option value="venue_manager">Gestores</option></select><Button type="submit">Filtrar</Button></form><div className="grid min-w-0 gap-6 xl:grid-cols-2"><DashboardSection title="A seguir" description={`${filteredFollowing.length} resultados`}>{list(visibleFollowing,true)}{filteredFollowing.length>0&&<div className="mt-4 flex items-center justify-between border-t pt-3"><Button asChild variant="outline" size="sm" className={fPage<=1?'pointer-events-none opacity-50':''}><Link href={href(fPage-1,rPage,q,type)}><ChevronLeft className="h-4 w-4"/>Anterior</Link></Button><span className="text-xs">{fPage}/{fPages}</span><Button asChild variant="outline" size="sm" className={fPage>=fPages?'pointer-events-none opacity-50':''}><Link href={href(fPage+1,rPage,q,type)}>Seguinte<ChevronRight className="h-4 w-4"/></Link></Button></div>}</DashboardSection><DashboardSection title="Seguidores" description={`${filteredFollowers.length} resultados`}>{list(visibleFollowers,false)}{filteredFollowers.length>0&&<div className="mt-4 flex items-center justify-between border-t pt-3"><Button asChild variant="outline" size="sm" className={rPage<=1?'pointer-events-none opacity-50':''}><Link href={href(fPage,rPage-1,q,type)}><ChevronLeft className="h-4 w-4"/>Anterior</Link></Button><span className="text-xs">{rPage}/{rPages}</span><Button asChild variant="outline" size="sm" className={rPage>=rPages?'pointer-events-none opacity-50':''}><Link href={href(fPage,rPage+1,q,type)}>Seguinte<ChevronRight className="h-4 w-4"/></Link></Button></div>}</DashboardSection></div></DashboardPage>
}
