import Link from 'next/link'
import Image from 'next/image'
import { format } from 'date-fns'
import { pt } from 'date-fns/locale'
import { Clock, Heart, MapPin, Navigation } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { CategoryIcon } from '@/components/categories/category-icon'
import { cn } from '@/lib/utils'
import type { Category, Event } from '@/lib/types'

type DiscoveryEvent=Event&{category?:Category|null;distanceKm?:number|null}
interface EventCardProps{event:DiscoveryEvent;variant?:'default'|'compact'|'horizontal';showFavoriteButton?:boolean;isFavorited?:boolean;onFavoriteToggle?:(id:string)=>void;className?:string}
function distanceLabel(value?:number|null){if(value==null)return null;return value<1?`${Math.round(value*1000)} m`:`${value.toFixed(1)} km`}

export function EventCard({event,variant='default',showFavoriteButton=false,isFavorited=false,onFavoriteToggle,className}:EventCardProps){
 const placeholder='https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop';const start=event.start_date?new Date(event.start_date):null;const end=event.end_date?new Date(event.end_date):null;const day=start?format(start,'d',{locale:pt}):'—';const month=start?format(start,'MMM',{locale:pt}).toUpperCase():'—';const distance=distanceLabel(event.distanceKm);const price=(!event.price_min&&!event.price_max)?'Grátis':event.price_min===event.price_max?`${event.price_min} €`:`Desde ${event.price_min||0} €`;const focusClass='focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2'
 if(variant==='horizontal')return <Card className={cn('overflow-hidden transition-shadow hover:shadow-md',className)}><Link href={`/eventos/${event.slug||event.id}`} className={cn('block',focusClass)}><CardContent className="flex gap-3 p-0"><div className="relative h-24 w-28 shrink-0"><Image src={event.image_url||placeholder} alt={event.title} fill className="object-cover"/><span className="absolute left-2 top-2 rounded-md bg-primary px-2 py-1 text-[10px] font-bold text-primary-foreground">{day} {month}</span></div><div className="min-w-0 flex-1 py-3 pr-3"><h3 className="line-clamp-1 font-semibold">{event.title}</h3><p className="mt-1 text-xs text-muted-foreground"><Clock className="mr-1 inline h-3.5 w-3.5"/>{start?format(start,'HH:mm'):'--:--'}{end?`–${format(end,'HH:mm')}`:''}</p><div className="mt-2 flex items-center justify-between gap-2 text-xs">{distance&&<span className="text-muted-foreground"><Navigation className="mr-1 inline h-3.5 w-3.5 text-primary"/>{distance}</span>}<strong className="text-primary">{price}</strong></div></div></CardContent></Link></Card>
 return <Card className={cn('group overflow-hidden border-border/70 transition hover:border-primary/35 hover:shadow-md',className)}><Link href={`/eventos/${event.slug||event.id}`} className={cn('block h-full',focusClass)}><div className="relative aspect-[16/9] overflow-hidden bg-muted"><Image src={event.image_url||placeholder} alt={event.title} fill className="object-cover transition-transform duration-300 group-hover:scale-[1.03]"/><div className="absolute left-2 top-2 rounded-lg bg-primary px-2 py-1 text-center text-primary-foreground shadow"><span className="block text-base font-bold leading-none">{day}</span><span className="text-[9px] font-semibold">{month}</span></div>{distance&&<span className="absolute bottom-2 right-2 rounded-full bg-background/95 px-2 py-1 text-[10px] font-semibold shadow-sm"><Navigation className="mr-1 inline h-3 w-3 text-primary"/>{distance}</span>}{event.is_featured&&<Badge className="absolute right-2 top-2 bg-amber-500 px-2 py-0.5 text-[10px]">Destaque</Badge>}{showFavoriteButton&&<Button variant="secondary" size="icon" aria-label={isFavorited?`Remover ${event.title} dos favoritos`:`Adicionar ${event.title} aos favoritos`} className="absolute right-2 top-2 h-11 w-11 rounded-full shadow-sm focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2" onClick={e=>{e.preventDefault();onFavoriteToggle?.(event.id)}}><Heart className={cn('h-4 w-4',isFavorited&&'fill-destructive text-destructive')}/></Button>}</div><CardContent className="p-3"><h3 className="line-clamp-1 text-sm font-semibold sm:text-base">{event.title}</h3><div className="mt-1.5 space-y-1 text-xs text-muted-foreground"><p><Clock className="mr-1 inline h-3.5 w-3.5"/>{start?format(start,'HH:mm'):'--:--'}{end?`–${format(end,'HH:mm')}`:''}</p>{event.address&&<p className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{event.address}</span></p>}</div><div className="mt-2 flex min-h-6 items-center justify-between gap-2">{event.category?<Badge variant="secondary" className="max-w-[58%] gap-1 truncate text-[10px]"><CategoryIcon iconKey={event.category.icon_key} slug={event.category.slug} name={event.category.name} className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{event.category.name}</span></Badge>:<span/>}<strong className="shrink-0 text-xs text-primary">{price}</strong></div></CardContent></Link></Card>
}
interface EventGridProps{events:DiscoveryEvent[];variant?:'default'|'compact'|'horizontal';columns?:2|3|4;showFavoriteButton?:boolean;favoritedIds?:string[];onFavoriteToggle?:(id:string)=>void;className?:string}
export function EventGrid({events,variant='default',columns=3,showFavoriteButton=false,favoritedIds=[],onFavoriteToggle,className}:EventGridProps){const gridCols={2:'grid-cols-1 sm:grid-cols-2',3:'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3',4:'grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4'};if(variant==='horizontal')return <div className={cn('flex flex-col gap-3',className)}>{events.map(event=><EventCard key={event.id} event={event} variant="horizontal" showFavoriteButton={showFavoriteButton} isFavorited={favoritedIds.includes(event.id)} onFavoriteToggle={onFavoriteToggle}/>)}</div>;return <div className={cn('grid gap-4',gridCols[columns],className)}>{events.map(event=><EventCard key={event.id} event={event} variant={variant} showFavoriteButton={showFavoriteButton} isFavorited={favoritedIds.includes(event.id)} onFavoriteToggle={onFavoriteToggle}/>)}</div>}
