'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import { Bell, ChevronDown, Heart, LayoutDashboard, LogIn, LogOut, Menu, Search, Settings, User } from 'lucide-react'
import { ThemeToggle } from '@/components/theme-toggle'
import { Button } from '@/components/ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
import { mobileSecondaryNavigation, publicPrimaryNavigation, publicSecondaryNavigation } from '@/lib/navigation/public'
import { createClient } from '@/lib/supabase/client'

interface HeaderProps {
  user?: { id: string; email: string; full_name?: string; avatar_url?: string } | null
  notificationCount?: number
}

export function Header({ user, notificationCount = 0 }: HeaderProps) {
  const pathname = usePathname()
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const [unread, setUnread] = useState(notificationCount)
  const userId = user?.id

  useEffect(() => {
    if (!userId) return
    const supabase = createClient()
    let active = true
    const refresh = async () => {
      const { count } = await supabase.from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', userId).is('read_at', null)
      if (active) setUnread(count || 0)
    }
    void refresh()
    const channel = supabase.channel(`header-notifications-${userId}`).on('postgres_changes', { event: '*', schema: 'public', table: 'notifications', filter: `user_id=eq.${userId}` }, () => { void refresh() }).subscribe()
    return () => { active = false; void supabase.removeChannel(channel) }
  }, [userId])

  return <header className="sticky top-0 z-50 w-full border-b border-border/50 bg-background/92 backdrop-blur-xl supports-[backdrop-filter]:bg-background/80"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-3 sm:px-6 lg:px-8"><Link href="/" className="flex min-h-11 items-center gap-2.5" aria-label="FIND4SPORT - início"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-teal-400 shadow-sm"><span className="text-sm font-bold text-white">F4S</span></div><span className="hidden text-xl font-bold tracking-tight sm:block">FIND<span className="text-primary">4</span>SPORT</span></Link>
    <nav className="hidden items-center gap-1 md:flex" aria-label="Navegação principal">{publicPrimaryNavigation.map(item => { const active = pathname === item.href || pathname.startsWith(`${item.href}/`); return <Link key={item.href} href={item.href} className={cn('flex min-h-11 items-center gap-2 rounded-lg px-3 py-2 text-sm font-medium transition-colors', active ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground')}><item.icon className="h-4 w-4" />{item.name}</Link> })}<DropdownMenu><DropdownMenuTrigger className={cn('flex min-h-11 items-center gap-1 rounded-lg px-3 py-2 text-sm font-medium', publicSecondaryNavigation.some(i => pathname === i.href || pathname.startsWith(`${i.href}/`)) ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent')}>Explorar <ChevronDown className="h-4 w-4" /></DropdownMenuTrigger><DropdownMenuContent align="start">{publicSecondaryNavigation.map(item => <DropdownMenuItem key={item.href} render={<Link href={item.href} className="flex min-h-10 cursor-pointer items-center"><item.icon className="mr-2 h-4 w-4" />{item.name}</Link>} />)}</DropdownMenuContent></DropdownMenu></nav>
    <div className="flex items-center gap-1 sm:gap-2"><div className="hidden sm:block"><ThemeToggle /></div><Button variant="ghost" size="icon" asChild className="hidden h-11 w-11 sm:flex"><Link href="/pesquisa" aria-label="Pesquisar"><Search className="h-5 w-5" /></Link></Button>{user ? <><Button variant="ghost" size="icon" asChild className="relative h-11 w-11"><Link href="/dashboard/notificacoes" aria-label="Notificações"><Bell className="h-5 w-5" />{unread > 0 && <Badge variant="destructive" className="absolute right-0.5 top-0.5 h-5 min-w-5 rounded-full px-1 text-[10px]">{unread > 9 ? '9+' : unread}</Badge>}</Link></Button><DropdownMenu><DropdownMenuTrigger className="relative hidden h-11 w-11 items-center justify-center rounded-full md:flex" aria-label="Abrir menu da conta"><Avatar className="h-9 w-9"><AvatarImage src={user.avatar_url || undefined} /><AvatarFallback className="bg-primary font-bold text-primary-foreground">{user.full_name?.charAt(0) || user.email.charAt(0).toUpperCase()}</AvatarFallback></Avatar></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-60"><div className="p-2"><p className="truncate text-sm font-medium">{user.full_name || 'Utilizador'}</p><p className="truncate text-xs text-muted-foreground">{user.email}</p></div><DropdownMenuSeparator /><DropdownMenuItem render={<Link href="/dashboard" className="flex min-h-10 cursor-pointer items-center font-semibold text-primary"><LayoutDashboard className="mr-2 h-4 w-4" />Painel</Link>} /><DropdownMenuItem render={<Link href="/dashboard/perfil" className="flex min-h-10 cursor-pointer items-center"><User className="mr-2 h-4 w-4" />O Meu Perfil</Link>} /><DropdownMenuItem render={<Link href="/dashboard/favoritos" className="flex min-h-10 cursor-pointer items-center"><Heart className="mr-2 h-4 w-4" />Favoritos</Link>} /><DropdownMenuItem render={<Link href="/dashboard/definicoes" className="flex min-h-10 cursor-pointer items-center"><Settings className="mr-2 h-4 w-4" />Definições</Link>} /><DropdownMenuSeparator /><DropdownMenuItem render={<Link href="/auth/logout" prefetch={false} className="flex min-h-10 cursor-pointer items-center text-destructive"><LogOut className="mr-2 h-4 w-4" />Terminar sessão</Link>} /></DropdownMenuContent></DropdownMenu></> : <><Button variant="ghost" asChild className="hidden min-h-11 sm:flex"><Link href="/auth/login"><LogIn className="mr-2 h-4 w-4" />Entrar</Link></Button><Button asChild size="sm" className="hidden min-h-11 sm:inline-flex"><Link href="/auth/registar">Registar</Link></Button></>}
      <Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}><SheetTrigger render={<Button variant="ghost" size="icon" className="h-11 w-11 md:hidden" aria-label="Mais opções"><Menu className="h-5 w-5" /></Button>} /><SheetContent side="right" className="flex h-[100dvh] max-h-[100dvh] w-[min(86vw,320px)] min-h-0 flex-col overflow-hidden p-0"><SheetHeader className="shrink-0 border-b p-4 text-left"><SheetTitle>Mais</SheetTitle></SheetHeader><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-3 pb-[calc(1rem+env(safe-area-inset-bottom))]"><div className="flex flex-col gap-1"><p className="px-3 pb-1 pt-2 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">Explorar</p>{mobileSecondaryNavigation.map(item => <Link key={item.href} href={item.href} onClick={() => setMobileMenuOpen(false)} className={cn('flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm', pathname === item.href || pathname.startsWith(`${item.href}/`) ? 'bg-primary/10 font-semibold text-primary' : 'text-muted-foreground hover:bg-muted hover:text-foreground')}><item.icon className="h-5 w-5" />{item.name}</Link>)}<div className="my-2 border-t" />{user ? <><div className="mb-2 flex items-center gap-3 rounded-xl bg-muted/40 p-3"><Avatar className="h-10 w-10"><AvatarImage src={user.avatar_url || undefined} /><AvatarFallback>{user.full_name?.charAt(0) || 'U'}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-sm font-semibold">{user.full_name || 'Utilizador'}</p><p className="truncate text-xs text-muted-foreground">{user.email}</p></div></div><Link href="/dashboard" onClick={() => setMobileMenuOpen(false)} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold text-primary"><LayoutDashboard className="h-5 w-5" />Painel</Link><Link href="/dashboard/favoritos" onClick={() => setMobileMenuOpen(false)} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-muted-foreground"><Heart className="h-5 w-5" />Favoritos</Link><Link href="/dashboard/definicoes" onClick={() => setMobileMenuOpen(false)} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-muted-foreground"><Settings className="h-5 w-5" />Definições</Link><Link href="/auth/logout" prefetch={false} onClick={() => setMobileMenuOpen(false)} className="flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm text-destructive"><LogOut className="h-5 w-5" />Terminar sessão</Link></> : <div className="grid gap-2"><Button asChild variant="outline" className="min-h-11"><Link href="/auth/login" onClick={() => setMobileMenuOpen(false)}>Entrar</Link></Button><Button asChild className="min-h-11"><Link href="/auth/registar" onClick={() => setMobileMenuOpen(false)}>Criar conta</Link></Button></div>}<div className="mt-3 border-t pt-3 sm:hidden"><ThemeToggle /></div></div></div></SheetContent></Sheet></div></div></header>
}
