'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Bell, Calendar, Check, CreditCard, Info, MessageSquare, Star, Trash2, Users } from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { pt } from 'date-fns/locale'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { deleteNotificationAction, markAllNotificationsAsRead, markNotificationAsRead } from '@/app/actions/notifications'
import { useModal } from '@/components/providers/modal-provider'
import { DashboardEmptyState, DashboardPage, DashboardPageHeader, DashboardSection, DashboardStat, DashboardStatGrid } from '@/components/patterns/dashboard-page'
import { createClient } from '@/lib/supabase/client'

export type Notification = { id:string; type:string; message:string; read_at:string|null; created_at:string; link:string|null; data?:Record<string,unknown> }
function notificationMeta(type:string){if(type==='event')return{label:'Evento',icon:Calendar};if(type==='message')return{label:'Mensagem',icon:MessageSquare};if(type==='review')return{label:'Avaliação',icon:Star};if(type==='billing')return{label:'Faturação',icon:CreditCard};if(type==='reservation')return{label:'Reserva',icon:Calendar};if(type==='community')return{label:'Comunidade',icon:Users};return{label:'Geral',icon:Info}}

export function NotificationsInterface({initialNotifications,currentUserId}:{initialNotifications:Notification[];currentUserId:string}){
  const [notifications,setNotifications]=useState(initialNotifications);const {showAlert,showConfirm}=useModal();const unreadCount=notifications.filter(n=>!n.read_at).length
  useEffect(()=>{const supabase=createClient();const channel=supabase.channel(`notifications-${currentUserId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${currentUserId}`},payload=>{const n=payload.new as Notification;setNotifications(prev=>prev.some(x=>x.id===n.id)?prev:[n,...prev])}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'notifications',filter:`user_id=eq.${currentUserId}`},payload=>{const n=payload.new as Notification;setNotifications(prev=>prev.map(x=>x.id===n.id?n:x))}).on('postgres_changes',{event:'DELETE',schema:'public',table:'notifications',filter:`user_id=eq.${currentUserId}`},payload=>{const id=(payload.old as any)?.id;setNotifications(prev=>prev.filter(x=>x.id!==id))}).subscribe();return()=>{void supabase.removeChannel(channel)}},[currentUserId])
  async function markAll(){const previous=notifications;setNotifications(list=>list.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));try{await markAllNotificationsAsRead()}catch(error){setNotifications(previous);showAlert('Erro',error instanceof Error?error.message:'Não foi possível atualizar as notificações.','error')}}
  async function markOne(id:string){const current=notifications.find(n=>n.id===id);if(!current||current.read_at)return;setNotifications(list=>list.map(n=>n.id===id?{...n,read_at:new Date().toISOString()}:n));try{await markNotificationAsRead(id)}catch(error){setNotifications(list=>list.map(n=>n.id===id?current:n));showAlert('Erro',error instanceof Error?error.message:'Não foi possível marcar como lida.','error')}}
  async function remove(id:string){if(!await showConfirm('Eliminar notificação','Esta notificação será removida da tua lista.',{confirmLabel:'Eliminar',destructive:true}))return;const previous=notifications;setNotifications(list=>list.filter(n=>n.id!==id));try{await deleteNotificationAction(id)}catch(error){setNotifications(previous);showAlert('Erro',error instanceof Error?error.message:'Não foi possível eliminar a notificação.','error')}}
  return <DashboardPage><DashboardPageHeader title="Notificações" description="Atualizações em tempo real de mensagens, reservas, eventos, comunidades, avaliações e faturação." action={unreadCount>0?<Button variant="outline" className="min-h-11" onClick={markAll}><Check className="mr-2 h-4 w-4"/>Marcar todas como lidas</Button>:undefined}/><DashboardStatGrid><DashboardStat label="Total" value={notifications.length} icon={<Bell className="h-5 w-5"/>}/><DashboardStat label="Não lidas" value={unreadCount} icon={<Bell className="h-5 w-5"/>}/><DashboardStat label="Lidas" value={notifications.length-unreadCount} icon={<Check className="h-5 w-5"/>}/><DashboardStat label="Com destino" value={notifications.filter(n=>Boolean(n.link)).length} icon={<Info className="h-5 w-5"/>}/></DashboardStatGrid><DashboardSection title="Atividade" description="Novas notificações entram automaticamente sem recarregar a página.">{notifications.length===0?<DashboardEmptyState icon={<Bell className="h-10 w-10"/>} title="Sem notificações" description="Está tudo em dia. Novas atualizações aparecerão aqui."/>:<div className="space-y-3">{notifications.map(n=>{const meta=notificationMeta(n.type);const Icon=meta.icon;const read=Boolean(n.read_at);return <article key={n.id} className={`rounded-2xl border p-4 ${read?'border-border bg-card':'border-primary/25 bg-primary/[0.03]'}`}><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-muted text-primary"><Icon className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge variant={read?'outline':'default'}>{meta.label}</Badge>{!read&&<span className="text-xs font-semibold text-primary">Nova</span>}</div><p className="mt-2 text-sm leading-relaxed">{n.message}</p><p className="mt-2 text-xs text-muted-foreground">{formatDistanceToNow(new Date(n.created_at),{addSuffix:true,locale:pt})}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:flex">{!read&&<Button variant="outline" className="min-h-11" onClick={()=>markOne(n.id)}><Check className="mr-2 h-4 w-4"/>Marcar lida</Button>}{n.link&&<Button asChild variant="outline" className="min-h-11"><Link href={n.link} onClick={()=>void markOne(n.id)}>Abrir</Link></Button>}<Button variant="ghost" className="min-h-11 text-destructive sm:ml-auto" onClick={()=>remove(n.id)}><Trash2 className="mr-2 h-4 w-4"/>Eliminar</Button></div></div></div></article>})}</div>}</DashboardSection></DashboardPage>
}
