import Link from 'next/link'
import Image from 'next/image'
import { BadgeCheck, Heart, MapPin, Navigation, Star } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { CategoryIcon } from '@/components/categories/category-icon'
import { cn } from '@/lib/utils'
import type { Category, SportSpace } from '@/lib/types'

type DiscoverySpace=SportSpace&{categories?:Category[];distanceKm?:number|null;averagePrice?:number|null}
interface SpaceCardProps{space:DiscoverySpace;variant?:'default'|'compact'|'horizontal';showFavoriteButton?:boolean;isFavorited?:boolean;onFavoriteToggle?:(id:string)=>void;className?:string}
function distanceLabel(value?:number|null){if(value==null)return null;return value<1?`${Math.round(value*1000)} m`:`${value.toFixed(1)} km`}
function money(value?:number|null){return value==null?null:new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(value)}
export function SpaceCard({space,variant='default',showFavoriteButton=false,isFavorited=false,onFavoriteToggle,className}:SpaceCardProps){
 const placeholder='https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=400&fit=crop';const distance=distanceLabel(space.distanceKm);const price=money(space.averagePrice);const focusClass='focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2';const category=space.categories?.[0]
 if(variant==='horizontal')return <Card className={cn('overflow-hidden transition-shadow hover:shadow-md',className)}><Link href={`/espacos/${space.slug||space.id}`} className={cn('block',focusClass)}><CardContent className="flex gap-3 p-0"><div className="relative h-24 w-28 shrink-0"><Image src={space.gallery_urls?.[0]||placeholder} alt={space.name} fill className="object-cover"/></div><div className="min-w-0 flex-1 py-3 pr-3"><div className="flex items-start justify-between gap-2"><h3 className="line-clamp-1 flex items-center gap-1 font-semibold">{space.name}{space.is_verified&&<BadgeCheck className="h-4 w-4 text-primary"/>}</h3>{space.rating_avg!=null&&<span className="flex items-center gap-1 text-xs font-semibold"><Star className="h-3.5 w-3.5 fill-amber-500 text-amber-500"/>{space.rating_avg.toFixed(1)}</span>}</div><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs">{distance&&<span className="text-muted-foreground"><Navigation className="mr-1 inline h-3.5 w-3.5 text-primary"/>{distance}</span>}{price&&<strong className="text-primary">Média {price}/h</strong>}</div></div></CardContent></Link></Card>
 return <Card className={cn('group overflow-hidden border-border/70 transition hover:border-primary/35 hover:shadow-md',className)}><Link href={`/espacos/${space.slug||space.id}`} className={cn('block h-full',focusClass)}><div className="relative aspect-[16/10] overflow-hidden bg-muted"><Image src={space.gallery_urls?.[0]||placeholder} alt={space.name} fill className="object-cover transition-transform duration-300 group-hover:scale-[1.03]"/>{space.ownership_status==='unclaimed'&&<Badge variant="outline" className="absolute left-2 top-2 bg-background/90 px-2 py-0.5 text-[10px]">Sem proprietário</Badge>}{distance&&<span className="absolute bottom-2 right-2 rounded-full bg-background/95 px-2 py-1 text-[10px] font-semibold shadow-sm"><Navigation className="mr-1 inline h-3 w-3 text-primary"/>{distance}</span>}{showFavoriteButton&&<Button variant="secondary" size="icon" aria-label={isFavorited?`Remover ${space.name} dos favoritos`:`Adicionar ${space.name} aos favoritos`} className="absolute right-2 top-2 h-11 w-11 rounded-full shadow-sm focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2" onClick={e=>{e.preventDefault();onFavoriteToggle?.(space.id)}}><Heart className={cn('h-4 w-4',isFavorited&&'fill-destructive text-destructive')}/></Button>}</div><CardContent className="p-3"><div className="flex items-start justify-between gap-2"><h3 className="line-clamp-1 flex min-w-0 items-center gap-1 text-sm font-semibold sm:text-base">{space.name}{space.is_verified&&<BadgeCheck className="h-4 w-4 shrink-0 text-primary"/>}</h3>{space.rating_avg!=null&&<span className="flex shrink-0 items-center gap-1 text-xs font-semibold"><Star className="h-3.5 w-3.5 fill-amber-500 text-amber-500"/>{space.rating_avg.toFixed(1)}</span>}</div>{space.address&&<p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{space.address}</span></p>}<div className="mt-2 flex min-h-6 items-center justify-between gap-2">{category?<Badge variant="secondary" className="max-w-[58%] gap-1 truncate text-[10px]"><CategoryIcon iconKey={category.icon_key} slug={category.slug} name={category.name} className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{category.name}</span></Badge>:<span/>}{price&&<span className="shrink-0 text-xs font-bold text-primary">Média {price}/h</span>}</div><p className="mt-1 text-[10px] text-muted-foreground">{space.review_count??0} avaliações</p></CardContent></Link></Card>
}
interface SpaceGridProps{spaces:DiscoverySpace[];variant?:'default'|'compact'|'horizontal';columns?:2|3|4;showFavoriteButton?:boolean;favoritedIds?:string[];onFavoriteToggle?:(id:string)=>void;className?:string}
export function SpaceGrid({spaces,variant='default',columns=3,showFavoriteButton=false,favoritedIds=[],onFavoriteToggle,className}:SpaceGridProps){const gridCols={2:'grid-cols-1 sm:grid-cols-2',3:'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3',4:'grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4'};if(variant==='horizontal')return <div className={cn('flex flex-col gap-3',className)}>{spaces.map(space=><SpaceCard key={space.id} space={space} variant="horizontal" showFavoriteButton={showFavoriteButton} isFavorited={favoritedIds.includes(space.id)} onFavoriteToggle={onFavoriteToggle}/>)}</div>;return <div className={cn('grid gap-4',gridCols[columns],className)}>{spaces.map(space=><SpaceCard key={space.id} space={space} variant={variant} showFavoriteButton={showFavoriteButton} isFavorited={favoritedIds.includes(space.id)} onFavoriteToggle={onFavoriteToggle}/>)}</div>}
