import { Search } from 'lucide-react'
import { createAdminClient } from '@/lib/supabase/admin'
import { cookies } from 'next/headers'
import { PesquisaFiltros } from '@/components/pesquisa-filtros'
import { PesquisaMapWrapper } from '@/components/pesquisa-map-wrapper'
import { PesquisaLayout } from '@/components/pesquisa-layout'
import { SearchResultsList } from '@/components/search-results-list'
import type { TaxonomyOption } from '@/components/taxonomy-combobox'
import { parseSearchFilters } from '@/lib/search/filters'
import { distanceFrom, parseGeoCookie } from '@/lib/geo'

export const dynamic = 'force-dynamic'

export interface UnifiedResultItem { id:string;itemType:'space'|'professional'|'event'|'community';title:string;subtitle:string;address:string;mapAddress?:string|null;rating_avg:number|null;review_count:number|null;is_verified:boolean;image_url?:string|null;link:string;created_at?:string|null;start_date?:string|null;latitude?:number|null;longitude?:number|null;distanceKm?:number|null;searchRank?:number }
type CategoryRow=TaxonomyOption
type TaxonomySearchRow={id:string;name:string;slug:string;parent_id:string|null;taxonomy_type?:string|null;is_active?:boolean|null}
function branchIds(categories:CategoryRow[],selectedId:string){const ids=new Set<string>([selectedId]);let changed=true;while(changed){changed=false;for(const c of categories)if(c.parent_id&&ids.has(c.parent_id)&&!ids.has(c.id)){ids.add(c.id);changed=true}}return[...ids]}
function normalize(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function matches(value:string|undefined|null,q:string){return Boolean(value&&normalize(value).includes(q))}
function textRank(item:UnifiedResultItem,query:string){if(!query)return item.searchRank||0;const title=normalize(item.title),q=normalize(query);return (item.searchRank||0)+(title===q?30:title.startsWith(q)?20:title.includes(q)?10:0)}

export default async function PesquisaPage({searchParams:promise}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const admin=createAdminClient();const cookieStore=await cookies();const userLocation=parseGeoCookie(cookieStore.get('f4s_geo')?.value);const searchParams=promise?await promise:{}
  const{category:categoryParam,query,location:locationParam,type:typeParam,rating:ratingParam,sort:sortParam,radius,dateFrom,dateTo}=parseSearchFilters(searchParams);const includeAll=typeParam==='todos';let results:UnifiedResultItem[]=[]
  const{data:rawCategories}=await admin.from('categories').select('id,name,slug,parent_id,taxonomy_type,is_active').order('name');const taxonomy=(rawCategories||[]) as TaxonomySearchRow[];const categories:CategoryRow[]=taxonomy.filter(row=>row.is_active!==false).map(r=>({id:r.id,name:r.name,slug:r.slug,emoji:null,parent_id:r.parent_id}))
  const selectedCategory=categoryParam?categories.find(c=>c.slug===categoryParam||c.id===categoryParam||normalize(c.name)===normalize(categoryParam)):null;const categoryIds=selectedCategory?branchIds(categories,selectedCategory.id):[];const categoryNames=selectedCategory?categories.filter(c=>categoryIds.includes(c.id)).map(c=>c.name):[]
  let professionalIds:string[]|null=null,spaceIds:string[]|null=null
  if(selectedCategory){const[p,s]=await Promise.all([admin.from('professional_categories').select('professional_id').in('category_id',categoryIds),admin.from('space_categories').select('space_id').in('category_id',categoryIds)]);professionalIds=[...new Set((p.data||[]).map(x=>x.professional_id))];spaceIds=[...new Set((s.data||[]).map(x=>x.space_id))]}

  if(includeAll||typeParam==='profissionais'){
    const q=normalize(query);let taxonomyProfessionalIds:string[]=[];const matchedTaxonomy=q?taxonomy.filter(c=>c.is_active!==false&&(matches(c.name,q)||matches(c.slug,q))):[]
    if(matchedTaxonomy.length){const matchedIds=[...new Set(matchedTaxonomy.flatMap(c=>branchIds(categories,c.id)))];const{data:links}=await admin.from('professional_categories').select('professional_id').in('category_id',matchedIds);taxonomyProfessionalIds=[...new Set((links||[]).map(x=>x.professional_id))]}
    let directIds:string[]=[]
    if(query){const{data:direct,error:directError}=await admin.from('professionals').select('id').eq('status','active').or(`full_name.ilike.%${query}%,professional_name.ilike.%${query}%,address.ilike.%${query}%,bio.ilike.%${query}%`).limit(200);if(directError)console.error('Public professional direct search:',directError);directIds=(direct||[]).map(p=>p.id)}
    const smartIds=query?[...new Set([...directIds,...taxonomyProfessionalIds])]:null
    let db=admin.from('professionals').select('id,full_name,professional_name,public_slug,address,bio,rating_avg,review_count,is_verified,avatar_url,created_at,latitude,longitude,status').eq('status','active');if(smartIds)db=smartIds.length?db.in('id',smartIds):db.eq('id','00000000-0000-0000-0000-000000000000');if(locationParam)db=db.ilike('address',`%${locationParam}%`);if(ratingParam)db=db.gte('rating_avg',ratingParam);if(selectedCategory)db=professionalIds?.length?db.in('id',professionalIds):db.eq('id','00000000-0000-0000-0000-000000000000');const{data,error}=await db.limit(100);if(error)console.error('Public professional search:',error)
    const ids=(data||[]).map(p=>p.id);const{data:links}=ids.length?await admin.from('professional_categories').select('professional_id,category_id').in('professional_id',ids):{data:[]};const categoryById=new Map(taxonomy.map(c=>[c.id,c]));const namesByProfessional=new Map<string,string[]>();for(const link of links||[]){const c=categoryById.get(link.category_id);if(c){const list=namesByProfessional.get(link.professional_id)||[];list.push(c.name);namesByProfessional.set(link.professional_id,list)}}
    results.push(...(data||[]).map(p=>{const taxonomyNames=namesByProfessional.get(p.id)||[];let rank=0;if(q){if(normalize(p.professional_name||p.full_name||'')===q)rank+=100;else if(matches(p.professional_name,q)||matches(p.full_name,q))rank+=70;if(matches(p.address,q))rank+=50;if(taxonomyNames.some(name=>normalize(name)===q))rank+=90;else if(taxonomyNames.some(name=>matches(name,q)))rank+=65;if(matches(p.bio,q))rank+=20}return{id:`pro-${p.id}`,itemType:'professional' as const,title:p.professional_name||p.full_name||'Profissional',subtitle:taxonomyNames.length?taxonomyNames.slice(0,4).join(' · '):(p.bio||'Profissional de desporto'),address:p.address||'',mapAddress:p.address,rating_avg:p.rating_avg,review_count:p.review_count,is_verified:Boolean(p.is_verified),image_url:p.avatar_url,link:`/profissionais/${p.public_slug||p.id}`,created_at:p.created_at,latitude:p.latitude,longitude:p.longitude,distanceKm:distanceFrom(userLocation,p.latitude,p.longitude),searchRank:rank}}))
  }
  if(includeAll||typeParam==='espacos'){let db=admin.from('sport_spaces').select('id,name,slug,address,description,rating_avg,review_count,is_verified,gallery_urls,cover_url,created_at,latitude,longitude,status').eq('status','active');if(query)db=db.or(`name.ilike.%${query}%,address.ilike.%${query}%,description.ilike.%${query}%`);if(locationParam)db=db.ilike('address',`%${locationParam}%`);if(ratingParam)db=db.gte('rating_avg',ratingParam);if(selectedCategory)db=spaceIds?.length?db.in('id',spaceIds):db.eq('id','00000000-0000-0000-0000-000000000000');const{data,error}=await db.limit(100);if(error)console.error('Public space search:',error);results.push(...(data||[]).map(s=>({id:`space-${s.id}`,itemType:'space' as const,title:s.name,subtitle:s.description||'Espaço desportivo',address:s.address||'',mapAddress:s.address,rating_avg:s.rating_avg,review_count:s.review_count,is_verified:Boolean(s.is_verified),image_url:s.cover_url||s.gallery_urls?.[0]||null,link:`/espacos/${s.slug||s.id}`,created_at:s.created_at,latitude:s.latitude,longitude:s.longitude,distanceKm:distanceFrom(userLocation,s.latitude,s.longitude)})))}
  if(includeAll||typeParam==='eventos'){let db=admin.from('events').select('id,title,address,description,image_url,created_at,start_date,latitude,longitude,status,category_id').eq('status','published').gte('start_date',new Date().toISOString());if(query)db=db.or(`title.ilike.%${query}%,address.ilike.%${query}%,description.ilike.%${query}%`);if(locationParam)db=db.ilike('address',`%${locationParam}%`);if(selectedCategory)db=db.in('category_id',categoryIds);if(dateFrom)db=db.gte('start_date',`${dateFrom}T00:00:00`);if(dateTo)db=db.lte('start_date',`${dateTo}T23:59:59`);const{data,error}=await db.limit(100);if(error)console.error('Public event search:',error);results.push(...(data||[]).map(e=>({id:`event-${e.id}`,itemType:'event' as const,title:e.title,subtitle:e.description||'Evento desportivo',address:e.address||'',mapAddress:e.address,rating_avg:null,review_count:null,is_verified:false,image_url:e.image_url,link:`/eventos/${e.id}`,created_at:e.created_at,start_date:e.start_date,latitude:e.latitude,longitude:e.longitude,distanceKm:distanceFrom(userLocation,e.latitude,e.longitude)})))}
  if(includeAll||typeParam==='comunidades'){let db=admin.from('communities').select('id,name,slug,description,sport_category,cover_url,is_private,created_at,location_scope,address,latitude,longitude').eq('is_private',false);if(query)db=db.or(`name.ilike.%${query}%,description.ilike.%${query}%,sport_category.ilike.%${query}%`);if(selectedCategory&&categoryNames.length)db=db.or(categoryNames.map(value=>`sport_category.ilike.%${value}%`).join(','));const{data,error}=await db.limit(100);if(error)console.error('Public community search:',error);results.push(...(data||[]).map(c=>({id:`community-${c.id}`,itemType:'community' as const,title:c.name,subtitle:c.description||c.sport_category||'Comunidade desportiva',address:c.location_scope==='online'?'Online':(c.address||c.sport_category||''),mapAddress:c.location_scope==='online'?null:c.address,rating_avg:null,review_count:null,is_verified:false,image_url:c.cover_url,link:`/comunidades/${c.slug||c.id}`,created_at:c.created_at,latitude:c.location_scope==='online'?null:c.latitude,longitude:c.location_scope==='online'?null:c.longitude,distanceKm:c.location_scope==='online'?null:distanceFrom(userLocation,c.latitude,c.longitude)})))}

  if(userLocation&&radius)results=results.filter(item=>item.distanceKm!=null&&item.distanceKm<=radius)
  if(sortParam==='rating')results.sort((a,b)=>Number(b.rating_avg||0)-Number(a.rating_avg||0));else if(sortParam==='newest')results.sort((a,b)=>new Date(b.start_date||b.created_at||0).getTime()-new Date(a.start_date||a.created_at||0).getTime());else results.sort((a,b)=>{const text=textRank(b,query)-textRank(a,query);if(text)return text;if(userLocation){const da=a.distanceKm??Infinity,db=b.distanceKm??Infinity;if(da!==db)return da-db}return Number(b.rating_avg||0)-Number(a.rating_avg||0)})
  const mapItems=results.filter(item=>(Number.isFinite(Number(item.latitude))&&Number.isFinite(Number(item.longitude)))||Boolean(item.mapAddress))
  return <PesquisaLayout resultsPane={<><PesquisaFiltros initialQuery={query} totalResults={results.length} initialSort={sortParam} categories={categories}/><div className="flex-1 overflow-y-auto bg-muted/10 p-3 sm:p-4">{!results.length?<div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><Search className="mb-4 h-8 w-8 text-primary"/><h2 className="text-lg font-semibold">Nenhum resultado encontrado</h2><p className="mt-2 text-sm text-muted-foreground">Reduz os filtros, o raio ou experimenta outra modalidade, profissão, especialidade, serviço ou localização.</p></div>:<SearchResultsList items={results}/>}</div></>} mapPane={<PesquisaMapWrapper items={mapItems} userLocation={userLocation}/>}/>
}
