'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { ArrowLeft, ArrowRight, Loader2, Trophy } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { registerProfessionalInitial } from '@/app/actions/register'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { TaxonomyCombobox, type TaxonomyOption } from '@/components/taxonomy-combobox'

type Step = 'perfil' | 'modalidades' | 'qualificacoes' | 'confirmar'
const STEPS: Array<{ id: Step; label: string }> = [{id:'perfil',label:'Perfil'},{id:'modalidades',label:'Modalidades'},{id:'qualificacoes',label:'Qualificações'},{id:'confirmar',label:'Confirmar'}]
const safeNext=(value:string|null)=>!value||!value.startsWith('/')||value.startsWith('//')?'/profissional/estado':value

export default function ProfessionalRegisterPage(){
  const router=useRouter(); const searchParams=useSearchParams(); const next=safeNext(searchParams.get('next'))
  const [step,setStep]=useState<Step>('perfil'); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null)
  const [userId,setUserId]=useState<string|null>(null); const [categories,setCategories]=useState<TaxonomyOption[]>([]); const [selectedCategories,setSelectedCategories]=useState<string[]>([])
  const [qualifications,setQualifications]=useState<Array<{title:string;issuer:string;issue_date:string}>>([]); const [newQualification,setNewQualification]=useState({title:'',issuer:'',issue_date:''})
  const [formData,setFormData]=useState({full_name:'',professional_name:'',bio:'',email:'',phone:'',whatsapp:'',address:'',website:'',service_radius_km:10,nif:''})

  useEffect(()=>{void(async()=>{const supabase=createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace(`/auth/registar?type=professional&next=${encodeURIComponent(next)}`);return}
    const [{data:existing},{data:categoryRows,error:categoriesError}]=await Promise.all([supabase.from('professionals').select('id').eq('user_id',user.id).maybeSingle(),supabase.from('categories').select('id,name,slug,parent_id,icon_key').order('name')]); if(existing){router.replace('/profissional/estado');return}
    if(categoriesError){setError('Não foi possível carregar as modalidades.');setLoading(false);return}
    setUserId(user.id); setCategories(categoryRows??[]); setFormData(current=>({...current,full_name:user.user_metadata?.full_name||'',email:user.email||''})); setLoading(false)})()},[next,router])

  const stepIndex=STEPS.findIndex(item=>item.id===step)
  const selectedNames=useMemo(()=>categories.filter(category=>selectedCategories.includes(category.id)).map(category=>category.name),[categories,selectedCategories])
  const nextStep=()=>{if(step==='perfil'&&formData.full_name.trim().length<2)return setError('Indica o teu nome completo.');if(step==='perfil'&&!formData.phone.trim())return setError('Indica um contacto telefónico.');if(step==='modalidades'&&!selectedCategories.length)return setError('Seleciona pelo menos uma modalidade.');setError(null);setStep(STEPS[Math.min(stepIndex+1,STEPS.length-1)].id)}
  const previousStep=()=>{setError(null);setStep(STEPS[Math.max(stepIndex-1,0)].id)}
  const addQualification=()=>{if(!newQualification.title.trim())return;setQualifications(current=>[...current,{title:newQualification.title.trim(),issuer:newQualification.issuer.trim(),issue_date:newQualification.issue_date||new Date().toISOString().slice(0,10)}]);setNewQualification({title:'',issuer:'',issue_date:''})}
  const submit=async()=>{if(!userId||saving)return;setSaving(true);setError(null);try{const result=await registerProfessionalInitial(formData.email,userId,{full_name:formData.full_name.trim(),professional_name:formData.professional_name.trim()||null,bio:formData.bio.trim()||null,email:formData.email,phone:formData.phone.trim()||null,whatsapp:formData.whatsapp.trim()||null,address:formData.address.trim()||null,website:formData.website.trim()||null,service_radius_km:formData.service_radius_km,nif:formData.nif.trim()||null,status:'pending',gallery_urls:null},selectedCategories,qualifications);if(result.error)throw new Error(result.error);router.replace(next)}catch(err){setError(err instanceof Error?err.message:'Não foi possível concluir o perfil profissional.')}finally{setSaving(false)}}

  if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary"/></div>
  return <main className="min-h-[calc(100dvh-4rem)] bg-muted/15 px-4 py-6 sm:px-6 sm:py-10"><div className="mx-auto max-w-4xl">
    <div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Onboarding · Profissional</p><h1 className="mt-2 text-3xl font-black tracking-tight">Cria o teu perfil profissional</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">A identidade já está autenticada. Aqui configuramos apenas informação profissional.</p></div>
    <div className="mb-5 rounded-2xl border border-border bg-card p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-muted-foreground">Passo {stepIndex+1} de {STEPS.length}</p><p className="font-bold">{STEPS[stepIndex].label}</p></div><div className="flex min-w-32 flex-1 gap-1.5 sm:max-w-xs">{STEPS.map((item,index)=><span key={item.id} className={`h-2 flex-1 rounded-full ${index<=stepIndex?'bg-primary':'bg-muted'}`}/>)}</div></div></div>
    <Card className="overflow-visible rounded-3xl"><CardHeader className="border-b border-border"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Trophy className="h-5 w-5"/></div><div><CardTitle>{STEPS[stepIndex].label}</CardTitle><CardDescription>{step==='perfil'?'Dados públicos e contactos profissionais.':step==='modalidades'?'Pesquisa e escolhe até cinco modalidades/áreas.':step==='qualificacoes'?'Adiciona certificações relevantes. Podes completar depois.':'Revê os dados antes de submeter.'}</CardDescription></div></div></CardHeader>
      <CardContent className="p-5 sm:p-7">
        {step==='perfil'&&<div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2"><Label>Nome completo *</Label><Input value={formData.full_name} onChange={e=>setFormData(current=>({...current,full_name:e.target.value}))} className="min-h-11"/></label><label className="space-y-2"><Label>Nome profissional</Label><Input value={formData.professional_name} onChange={e=>setFormData(current=>({...current,professional_name:e.target.value}))} placeholder="Ex.: Coach João Silva" className="min-h-11"/></label></div><label className="block space-y-2"><Label>Biografia</Label><Textarea rows={4} value={formData.bio} onChange={e=>setFormData(current=>({...current,bio:e.target.value}))} placeholder="Experiência, especialidades e abordagem profissional."/></label><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2"><Label>E-mail da conta</Label><Input value={formData.email} readOnly className="min-h-11 bg-muted/40"/></label><label className="space-y-2"><Label>Telemóvel *</Label><Input value={formData.phone} onChange={e=>setFormData(current=>({...current,phone:e.target.value}))} inputMode="tel" className="min-h-11"/></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2"><Label>WhatsApp</Label><Input value={formData.whatsapp} onChange={e=>setFormData(current=>({...current,whatsapp:e.target.value}))} className="min-h-11"/></label><label className="space-y-2"><Label>NIF</Label><Input value={formData.nif} onChange={e=>setFormData(current=>({...current,nif:e.target.value}))} inputMode="numeric" className="min-h-11"/></label></div><label className="block space-y-2"><Label>Morada / zona de atuação</Label><Input value={formData.address} onChange={e=>setFormData(current=>({...current,address:e.target.value}))} className="min-h-11"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2"><Label>Website</Label><Input value={formData.website} onChange={e=>setFormData(current=>({...current,website:e.target.value}))} placeholder="https://..." className="min-h-11"/></label><label className="space-y-2"><Label>Raio de atuação (km)</Label><Input type="number" min={0} max={500} value={formData.service_radius_km} onChange={e=>setFormData(current=>({...current,service_radius_km:Number(e.target.value)}))} className="min-h-11"/></label></div></div>}
        {step==='modalidades'&&<div className="space-y-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">Modalidades e especialidades</p><p className="mt-1 text-sm text-muted-foreground">Escreve algumas letras em vez de percorrer dezenas de opções. Categorias pai agrupam as especialidades.</p></div><Badge variant="secondary">{selectedCategories.length}/5</Badge></div><TaxonomyCombobox options={categories} value={selectedCategories} multiple maxSelected={5} onChange={value=>setSelectedCategories(Array.isArray(value)?value:[])} placeholder="Pesquisar modalidades" searchPlaceholder="Ex.: padel, futebol, pilates…"/></div>}
        {step==='qualificacoes'&&<div className="space-y-4"><div className="grid gap-3 md:grid-cols-[1fr_1fr_160px_auto]"><Input value={newQualification.title} onChange={e=>setNewQualification(current=>({...current,title:e.target.value}))} placeholder="Certificação" className="min-h-11"/><Input value={newQualification.issuer} onChange={e=>setNewQualification(current=>({...current,issuer:e.target.value}))} placeholder="Entidade" className="min-h-11"/><Input type="date" value={newQualification.issue_date} onChange={e=>setNewQualification(current=>({...current,issue_date:e.target.value}))} className="min-h-11"/><Button type="button" variant="outline" onClick={addQualification} className="min-h-11">Adicionar</Button></div>{qualifications.length===0?<div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Nenhuma qualificação adicionada. Este passo é opcional.</div>:<div className="space-y-2">{qualifications.map((qualification,index)=><div key={`${qualification.title}-${index}`} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{qualification.title}</p><p className="text-xs text-muted-foreground">{qualification.issuer||'Entidade não indicada'} · {qualification.issue_date}</p></div><Button type="button" variant="ghost" size="sm" onClick={()=>setQualifications(current=>current.filter((_,i)=>i!==index))}>Remover</Button></div>)}</div>}</div>}
        {step==='confirmar'&&<div className="space-y-4"><div className="rounded-2xl border bg-muted/20 p-4"><p className="text-sm font-bold">{formData.professional_name||formData.full_name}</p><p className="mt-1 text-sm text-muted-foreground">{formData.email} · {formData.phone}</p>{formData.bio&&<p className="mt-3 text-sm">{formData.bio}</p>}</div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">Modalidades</p><div className="flex flex-wrap gap-2">{selectedNames.map(name=><Badge key={name} variant="secondary">{name}</Badge>)}</div></div><div className="rounded-xl border border-border p-4 text-sm text-muted-foreground">O estado inicial e a verificação dependem da política de aprovação configurada na plataforma. Galeria, serviços e disponibilidade ficam no dashboard.</div></div>}
        {error&&<div role="alert" className="mt-5 rounded-xl border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>}
        <div className="mt-6 grid grid-cols-2 gap-3"><Button type="button" variant="outline" onClick={previousStep} disabled={stepIndex===0||saving} className="min-h-11"><ArrowLeft className="mr-2 h-4 w-4"/>Anterior</Button>{step==='confirmar'?<Button type="button" onClick={submit} disabled={saving} className="min-h-11">{saving?<><Loader2 className="mr-2 h-4 w-4 animate-spin"/>A guardar…</>:'Criar perfil'}</Button>:<Button type="button" onClick={nextStep} className="min-h-11">Continuar<ArrowRight className="ml-2 h-4 w-4"/></Button>}</div>
      </CardContent></Card>
  </div></main>
}
