'use client'

import { useState } from 'react'
import { Edit3, Plus, Power, ShieldCheck } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useModal } from '@/components/providers/modal-provider'
import { createAdministratorAction, setAdministratorActiveAction, updateAdministratorAction } from '@/app/admin/(dashboard)/administradores/actions'

type AdminRow = { id:string; auth_user_id:string|null; email:string; admin_type:string; created_at:string; active:boolean }
const types = [{value:'general',label:'Administrador Geral'},{value:'content',label:'Conteúdos'},{value:'support',label:'Suporte'},{value:'finance',label:'Financeiro'}]

export function AdministratorsManager({ initialRows }: { initialRows: AdminRow[] }) {
  const { showAlert, showConfirm } = useModal(); const [rows,setRows]=useState(initialRows); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<AdminRow|null>(null); const [busy,setBusy]=useState(false); const [form,setForm]=useState({email:'',adminType:'support'})
  function launch(row?:AdminRow){setEditing(row||null);setForm({email:row?.email||'',adminType:row?.admin_type||'support'});setOpen(true)}
  async function save(){setBusy(true);try{if(editing){const updated=await updateAdministratorAction(editing.id,form);setRows(v=>v.map(r=>r.id===editing.id?{...r,...updated}:r))}else{const created=await createAdministratorAction(form);setRows(v=>[{...created,active:true},...v])}setOpen(false);showAlert('Gestão atualizada',editing?'Administrador atualizado.':'Convite enviado ao novo administrador.','success')}catch(e){showAlert('Não foi possível guardar',e instanceof Error?e.message:'Erro inesperado.','error')}finally{setBusy(false)}}
  async function toggle(row:AdminRow){const ok=await showConfirm(row.active?'Desativar administrador':'Ativar administrador',`${row.active?'Bloquear':'Restaurar'} o acesso de ${row.email}?`,{confirmLabel:row.active?'Desativar':'Ativar',destructive:row.active});if(!ok)return;try{await setAdministratorActiveAction(row.id,!row.active);setRows(v=>v.map(r=>r.id===row.id?{...r,active:!r.active}:r));showAlert('Estado atualizado','A alteração já está em vigor.','success')}catch(e){showAlert('Erro',e instanceof Error?e.message:'Erro inesperado.','error')}}
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold sm:text-3xl">Administradores</h1><p className="mt-1 text-sm text-muted-foreground">Crie, edite, atribua funções e controle o acesso ao backoffice.</p></div><Button onClick={()=>launch()}><Plus className="mr-2 h-4 w-4"/>Novo administrador</Button></div><div className="grid gap-3">{rows.map(row=><article key={row.id} className="flex flex-col gap-3 rounded-2xl border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{row.email}</p><p className="text-xs text-muted-foreground">Desde {new Date(row.created_at).toLocaleDateString('pt-PT')}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant={row.active?'success':'secondary'}>{row.active?'Ativo':'Desativado'}</Badge><Badge variant="outline">{types.find(t=>t.value===row.admin_type)?.label||row.admin_type}</Badge><Button size="sm" variant="outline" onClick={()=>launch(row)}><Edit3 className="mr-2 h-4 w-4"/>Editar</Button><Button size="sm" variant="outline" onClick={()=>void toggle(row)}><Power className="mr-2 h-4 w-4"/>{row.active?'Desativar':'Ativar'}</Button></div></article>)}{rows.length===0&&<div className="rounded-2xl border border-dashed p-10 text-center"><ShieldCheck className="mx-auto h-10 w-10 text-muted-foreground"/><p className="mt-3">Sem administradores.</p></div>}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing?'Editar administrador':'Novo administrador'}</DialogTitle></DialogHeader><div className="space-y-4"><div><Label>Email</Label><Input className="mt-2" type="email" value={form.email} onChange={e=>setForm(v=>({...v,email:e.target.value}))}/></div><div><Label>Função</Label><select className="mt-2 min-h-11 w-full rounded-lg border bg-background px-3" value={form.adminType} onChange={e=>setForm(v=>({...v,adminType:e.target.value}))}>{types.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></div><Button className="w-full" disabled={busy||!form.email} onClick={()=>void save()}>{editing?'Guardar alterações':'Criar e enviar convite'}</Button></div></DialogContent></Dialog></div>
}
