'use client'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { useModal } from '@/components/providers/modal-provider'
import { updateAdminSpaceAction } from '@/app/admin/(dashboard)/espacos/actions'
export function SpaceDetailEditor({ space }: { space: { id: string; name: string; address?: string|null; description?: string|null; email?: string|null; phone?: string|null } }) { const { showAlert } = useModal(); const [form, setForm] = useState({ name: space.name || '', address: space.address || '', description: space.description || '', email: space.email || '', phone: space.phone || '' }); const [saving, setSaving] = useState(false); const set=(key:keyof typeof form,value:string)=>setForm(prev=>({...prev,[key]:value})); async function save(){setSaving(true);try{await updateAdminSpaceAction(space.id,form);showAlert('Espaço atualizado','As alterações foram guardadas.','success')}catch(error){showAlert('Erro',error instanceof Error?error.message:'Não foi possível guardar.','error')}finally{setSaving(false)}} return <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Nome *</Label><Input value={form.name} onChange={e=>set('name',e.target.value)} /></div><div className="space-y-2"><Label>Morada</Label><Input value={form.address} onChange={e=>set('address',e.target.value)} /></div><div className="space-y-2"><Label>Email</Label><Input type="email" value={form.email} onChange={e=>set('email',e.target.value)} /></div><div className="space-y-2"><Label>Telefone</Label><Input value={form.phone} onChange={e=>set('phone',e.target.value)} /></div><div className="space-y-2 sm:col-span-2"><Label>Descrição</Label><Textarea rows={5} value={form.description} onChange={e=>set('description',e.target.value)} /></div><div className="sm:col-span-2"><Button onClick={()=>void save()} disabled={saving}>{saving?'A guardar…':'Guardar alterações'}</Button></div></div> }
