'use server'
import {revalidatePath} from 'next/cache'
import {createClient} from '@/lib/supabase/server'
import {createAdminClient} from '@/lib/supabase/admin'
type I={name:string;description?:string|null;duration_minutes:number;price?:number|null;price_unit:string;modality:string}
async function ctx(){const s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)throw Error('Sessão inválida');const a=createAdminClient(),{data:p}=await a.from('professionals').select('id').eq('user_id',user.id).maybeSingle();if(!p)throw Error('Perfil profissional não encontrado');return{user,a:a as any,p:p.id}}
function clean(i:I){const name=i.name.trim(),duration_minutes=Number(i.duration_minutes),price=i.price==null?null:Number(i.price);if(!name||name.length>120)throw Error('Nome inválido.');if(!Number.isInteger(duration_minutes)||duration_minutes<15||duration_minutes>480)throw Error('Duração inválida.');if(price!==null&&(!Number.isFinite(price)||price<0))throw Error('Preço inválido.');return{name,description:i.description?.trim()||null,duration_minutes,price,price_unit:i.price_unit,modality:i.modality}}
export async function createService(i:I){const{a,p}=await ctx(),{data,error}=await a.from('services').insert({professional_id:p,...clean(i),is_active:false,moderation_status:'draft'}).select().single();if(error)throw error;revalidatePath('/dashboard/servicos');return data}
export async function updateService(id:string,i:I){const{a,p}=await ctx(),{data:old}=await a.from('services').select('moderation_status').eq('id',id).eq('professional_id',p).maybeSingle();if(!old)throw Error('Serviço não encontrado.');if(old.moderation_status==='pending')throw Error('Serviço em validação.');const reset=old.moderation_status==='approved'?{moderation_status:'draft',is_active:false,moderation_reason:null,submitted_at:null,reviewed_at:null,reviewed_by:null}:{};const{data,error}=await a.from('services').update({...clean(i),...reset}).eq('id',id).eq('professional_id',p).select().single();if(error)throw error;revalidatePath('/dashboard/servicos');return data}
export async function submitServiceForReview(id:string){const{user,a,p}=await ctx(),now=new Date().toISOString(),{data,error}=await a.from('services').update({moderation_status:'pending',is_active:false,moderation_reason:null,submitted_at:now}).eq('id',id).eq('professional_id',p).in('moderation_status',['draft','rejected']).select().maybeSingle();if(error||!data)throw Error(error?.message||'Não foi possível submeter.');await a.from('service_moderation_events').insert({service_id:id,event_type:'submitted',actor_user_id:user.id});revalidatePath('/dashboard/servicos');return data}
export async function toggleServiceActive(id:string,on:boolean){const{a,p}=await ctx();if(on){const{data:s}=await a.from('services').select('moderation_status').eq('id',id).eq('professional_id',p).maybeSingle();if(s?.moderation_status!=='approved')throw Error('O serviço precisa de aprovação.')}const{data,error}=await a.from('services').update({is_active:on}).eq('id',id).eq('professional_id',p).select().single();if(error)throw error;revalidatePath('/dashboard/servicos');return data}
export async function deleteService(id:string){const{a,p}=await ctx(),{error}=await a.from('services').delete().eq('id',id).eq('professional_id',p);if(error)throw error;revalidatePath('/dashboard/servicos')}
