'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { isFeatureEnabled } from '@/lib/billing/entitlements'

type PackageInput={serviceId:string;name:string;sessionsCount:number;price:number;validityDays?:number|null}
function missingTable(error:any){return ['42P01','PGRST205'].includes(String(error?.code||''))||String(error?.message||'').includes('service_packages')}
async function requirePremiumProfessional(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Sessão inválida.');const admin=createAdminClient();const{data:professional}=await admin.from('professionals').select('id').eq('user_id',user.id).maybeSingle();if(!professional)throw new Error('Perfil profissional não encontrado.');if(!(await isFeatureEnabled(user.id,'services.packages.enabled')))throw new Error('Os pacotes de sessões são exclusivos do plano Premium.');return{user,admin,professionalId:professional.id}}
function clean(input:PackageInput){const name=String(input.name||'').trim();if(name.length<2||name.length>120)throw new Error('Nome do pacote inválido.');const sessions=Number(input.sessionsCount);if(!Number.isInteger(sessions)||sessions<2||sessions>100)throw new Error('O pacote deve ter entre 2 e 100 sessões.');const price=Number(input.price);if(!Number.isFinite(price)||price<0||price>100000)throw new Error('Preço inválido.');const validity=input.validityDays==null?null:Number(input.validityDays);if(validity!==null&&(!Number.isInteger(validity)||validity<1||validity>730))throw new Error('A validade deve estar entre 1 e 730 dias.');return{name,sessions_count:sessions,price,validity_days:validity}}
export async function createServicePackage(input:PackageInput){const{admin,professionalId}=await requirePremiumProfessional();const{data:service}=await admin.from('services').select('id').eq('id',input.serviceId).eq('professional_id',professionalId).eq('is_active',true).maybeSingle();if(!service)throw new Error('Serviço inválido.');const db=admin as any;const{data,error}=await db.from('service_packages').insert({professional_id:professionalId,service_id:input.serviceId,...clean(input),is_active:true}).select('*').single();if(error){if(missingTable(error))throw new Error('O módulo de pacotes ainda não está ativo na base de dados.');throw error}revalidatePath('/dashboard/servicos');return data}
export async function toggleServicePackage(id:string,isActive:boolean){const{admin,professionalId}=await requirePremiumProfessional();const db=admin as any;const{data,error}=await db.from('service_packages').update({is_active:Boolean(isActive),updated_at:new Date().toISOString()}).eq('id',id).eq('professional_id',professionalId).select('*').single();if(error)throw error;revalidatePath('/dashboard/servicos');return data}
export async function deleteServicePackage(id:string){const{admin,professionalId}=await requirePremiumProfessional();const db=admin as any;const{error}=await db.from('service_packages').delete().eq('id',id).eq('professional_id',professionalId);if(error)throw error;revalidatePath('/dashboard/servicos')}
