import {redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import {createAdminClient} from '@/lib/supabase/admin'
import {ServicesManager} from '@/components/dashboard/services-manager'
import {ServicePackagesManager} from '@/components/dashboard/service-packages-manager'
import {ServiceModerationPanel} from '@/components/dashboard/service-moderation-panel'
import {isFeatureEnabled} from '@/lib/billing/entitlements'
function missingTable(e:any){return ['42P01','PGRST205'].includes(String(e?.code||''))||String(e?.message||'').includes('service_packages')}
export default async function ServicesPage(){const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login?redirect=/dashboard/servicos');const admin=createAdminClient(),{data:professional}=await admin.from('professionals').select('id').eq('user_id',user.id).maybeSingle();if(!professional)redirect('/dashboard');const[{data:services,error},packagesEnabled]=await Promise.all([(admin as any).from('services').select('*').eq('professional_id',professional.id).order('created_at',{ascending:false}),isFeatureEnabled(user.id,'services.packages.enabled')]);if(error)throw Error(`Não foi possível carregar os serviços: ${error.message}`);let packages:any[]=[],packagesAvailable=true;const r=await(admin as any).from('service_packages').select('*').eq('professional_id',professional.id).order('created_at',{ascending:false});if(r.error){if(missingTable(r.error))packagesAvailable=false;else throw Error(`Não foi possível carregar os pacotes: ${r.error.message}`)}else packages=r.data||[];return <div className="space-y-10"><ServicesManager initialServices={(services||[]) as any}/><ServiceModerationPanel services={services||[]}/><ServicePackagesManager services={(services||[]).filter((s:any)=>s.moderation_status==='approved')} initialPackages={packages} enabled={packagesEnabled} available={packagesAvailable}/></div>}
