insert into public.categories (name,slug,taxonomy_type,is_active,code) values
('Força e Potência','forca-potencia','specialty',true,'ESP-0001'),
('Condicionamento Físico','condicionamento-fisico','specialty',true,'ESP-0002'),
('Performance Desportiva','performance-desportiva','specialty',true,'ESP-0003'),
('Prevenção de Lesões','prevencao-lesoes','specialty',true,'ESP-0004'),
('Reabilitação Desportiva','reabilitacao-desportiva','specialty',true,'ESP-0005'),
('Retorno ao Desporto','retorno-desporto','specialty',true,'ESP-0006'),
('Mobilidade','mobilidade','specialty',true,'ESP-0007'),
('Flexibilidade','flexibilidade','specialty',true,'ESP-0008'),
('Resistência e Endurance','resistencia-endurance','specialty',true,'ESP-0009'),
('Velocidade e Agilidade','velocidade-agilidade','specialty',true,'ESP-0010'),
('Hipertrofia','hipertrofia','specialty',true,'ESP-0011'),
('Perda de Peso','perda-peso','specialty',true,'ESP-0012'),
('Composição Corporal','composicao-corporal','specialty',true,'ESP-0013'),
('Nutrição Desportiva','nutricao-desportiva','specialty',true,'ESP-0014'),
('Suplementação','suplementacao','specialty',true,'ESP-0015'),
('Performance Mental','performance-mental','specialty',true,'ESP-0016'),
('Gestão de Stress','gestao-stress','specialty',true,'ESP-0017'),
('Sono e Recuperação','sono-recuperacao','specialty',true,'ESP-0018'),
('Análise Técnica','analise-tecnica','specialty',true,'ESP-0019'),
('Análise Tática','analise-tatica','specialty',true,'ESP-0020'),
('Análise de Vídeo','analise-video','specialty',true,'ESP-0021'),
('Scouting e Talento','scouting-talento','specialty',true,'ESP-0022'),
('Formação Juvenil','formacao-juvenil','specialty',true,'ESP-0023'),
('Desporto Adaptado','desporto-adaptado','specialty',true,'ESP-0024'),
('Treino Individual','treino-individual','service',true,'SRV-0001'),
('Treino de Grupo','treino-grupo','service',true,'SRV-0002'),
('Treino de Equipa','treino-equipa','service',true,'SRV-0003'),
('Consulta Presencial','consulta-presencial','service',true,'SRV-0004'),
('Consulta Online','consulta-online','service',true,'SRV-0005'),
('Plano de Treino','plano-treino','service',true,'SRV-0006'),
('Plano Nutricional','plano-nutricional','service',true,'SRV-0007'),
('Avaliação Física','avaliacao-fisica','service',true,'SRV-0008'),
('Avaliação Funcional','avaliacao-funcional','service',true,'SRV-0009'),
('Avaliação de Performance','avaliacao-performance','service',true,'SRV-0010'),
('Sessão de Fisioterapia','sessao-fisioterapia','service',true,'SRV-0011'),
('Massagem Desportiva','massagem-desportiva','service',true,'SRV-0012'),
('Sessão de Recuperação','sessao-recuperacao','service',true,'SRV-0013'),
('Acompanhamento de Competição','acompanhamento-competicao','service',true,'SRV-0014'),
('Preparação para Competição','preparacao-competicao','service',true,'SRV-0015'),
('Análise de Vídeo','servico-analise-video','service',true,'SRV-0016'),
('Relatório de Performance','relatorio-performance','service',true,'SRV-0017'),
('Mentoria','mentoria','service',true,'SRV-0018'),
('Workshop','workshop','service',true,'SRV-0019'),
('Formação','formacao','service',true,'SRV-0020')
on conflict (slug) do update set taxonomy_type=excluded.taxonomy_type,is_active=true,code=coalesce(public.categories.code,excluded.code);
