-- Production maturity synchronization.
-- This migration consolidates the production-safe schema additions applied during the platform audit.

alter table public.notifications add column if not exists data jsonb not null default '{}'::jsonb;
alter table public.notifications add column if not exists dedupe_key text;
create unique index if not exists notifications_user_dedupe_idx on public.notifications(user_id,dedupe_key) where dedupe_key is not null;
create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id,created_at desc) where read_at is null;
do $$ begin if not exists(select 1 from pg_policies where schemaname='public' and tablename='notifications' and policyname='Users can delete their own notifications') then create policy "Users can delete their own notifications" on public.notifications for delete to authenticated using(auth.uid()=user_id); end if; end $$;
grant select,update,delete on public.notifications to authenticated;

alter table public.communities add column if not exists location_scope text not null default 'online';
alter table public.communities add column if not exists address text;
alter table public.communities add column if not exists latitude double precision;
alter table public.communities add column if not exists longitude double precision;
do $$ begin if not exists(select 1 from pg_constraint where conname='communities_location_scope_check') then alter table public.communities add constraint communities_location_scope_check check(location_scope in('online','local','regional','national')); end if; end $$;
create index if not exists communities_location_idx on public.communities(latitude,longitude) where latitude is not null and longitude is not null;

create table if not exists public.event_ticket_types(id uuid primary key default gen_random_uuid(),event_id uuid not null references public.events(id) on delete cascade,name text not null,description text,price numeric(10,2) not null check(price>=0),capacity integer check(capacity is null or capacity>0),is_active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists event_ticket_types_event_idx on public.event_ticket_types(event_id,is_active,sort_order);
alter table public.event_participants add column if not exists ticket_type_id uuid references public.event_ticket_types(id) on delete set null;
alter table public.event_participants add column if not exists amount numeric(10,2);
alter table public.event_ticket_types enable row level security;
do $$ begin if not exists(select 1 from pg_policies where schemaname='public' and tablename='event_ticket_types' and policyname='Public can read active event tickets') then create policy "Public can read active event tickets" on public.event_ticket_types for select using(is_active=true); end if; end $$;
grant select on public.event_ticket_types to anon,authenticated;
insert into public.event_ticket_types(event_id,name,price,sort_order) select e.id,'Entrada',coalesce(e.price_min,0),0 from public.events e where not exists(select 1 from public.event_ticket_types t where t.event_id=e.id) on conflict do nothing;

alter table public.messages add column if not exists legacy_status text;
do $$ begin if not exists(select 1 from pg_constraint where conname='messages_legacy_status_check') then alter table public.messages add constraint messages_legacy_status_check check(legacy_status is null or legacy_status='orphaned_no_business_context'); end if; end $$;
create index if not exists messages_legacy_status_idx on public.messages(legacy_status) where legacy_status is not null;

create or replace function public.push_notification(p_user_id uuid,p_type text,p_message text,p_link text default null,p_data jsonb default '{}'::jsonb,p_dedupe_key text default null) returns void language plpgsql security definer set search_path=public as $$ begin if p_user_id is null then return; end if; insert into public.notifications(user_id,type,message,link,data,dedupe_key) values(p_user_id,left(coalesce(p_type,'general'),50),p_message,p_link,coalesce(p_data,'{}'::jsonb),p_dedupe_key) on conflict(user_id,dedupe_key) where dedupe_key is not null do nothing; end $$;
revoke all on function public.push_notification(uuid,text,text,text,jsonb,text) from public,anon,authenticated;

create or replace function public.reservation_provider_user(p_professional_id uuid,p_space_id uuid) returns uuid language sql stable security definer set search_path=public as $$ select coalesce((select user_id from public.professionals where id=p_professional_id),(select owner_user_id from public.sport_spaces where id=p_space_id)) $$;
revoke all on function public.reservation_provider_user(uuid,uuid) from public,anon,authenticated;

create or replace function public.notify_message_insert() returns trigger language plpgsql security definer set search_path=public as $$ begin perform public.push_notification(new.receiver_id,'message','Recebeste uma nova mensagem.','/dashboard/mensagens'||case when new.thread_id is not null then '?thread='||new.thread_id::text else '' end,jsonb_build_object('message_id',new.id,'thread_id',new.thread_id,'sender_id',new.sender_id),'message:'||new.id::text); return new; end $$;
drop trigger if exists notify_message_insert on public.messages;create trigger notify_message_insert after insert on public.messages for each row execute function public.notify_message_insert();

create or replace function public.notify_reservation_change() returns trigger language plpgsql security definer set search_path=public as $$ declare provider_id uuid;label text;event_key text;begin provider_id:=public.reservation_provider_user(new.professional_id,new.space_id);if tg_op='INSERT' then if coalesce(new.status::text,'') not in('paid','confirmed') then return new;end if;label:='Reserva confirmada';event_key:='reservation:'||new.id::text||':'||new.status::text;elsif old.status is distinct from new.status then label:=case new.status::text when 'paid' then 'Reserva paga' when 'confirmed' then 'Reserva confirmada' when 'cancelled' then 'Reserva cancelada' when 'completed' then 'Reserva concluída' else 'Reserva atualizada' end;event_key:='reservation:'||new.id::text||':'||new.status::text;elsif old.payment_status is distinct from new.payment_status then label:=case new.payment_status when 'paid' then 'Pagamento da reserva confirmado' when 'refunded' then 'Reserva reembolsada' when 'failed' then 'Pagamento da reserva falhou' else 'Pagamento da reserva atualizado' end;event_key:='reservation-payment:'||new.id::text||':'||coalesce(new.payment_status,'unknown');else return new;end if;perform public.push_notification(new.user_id,'reservation',label,'/dashboard/agenda',jsonb_build_object('reservation_id',new.id,'status',new.status,'payment_status',new.payment_status),event_key||':buyer');if provider_id is not null and provider_id<>new.user_id then perform public.push_notification(provider_id,'reservation',label,'/dashboard/reservas',jsonb_build_object('reservation_id',new.id,'status',new.status,'payment_status',new.payment_status),event_key||':provider');end if;return new;end $$;
drop trigger if exists notify_reservation_change on public.reservations;create trigger notify_reservation_change after insert or update of status,payment_status on public.reservations for each row execute function public.notify_reservation_change();

create or replace function public.notify_reservation_change_request() returns trigger language plpgsql security definer set search_path=public as $$ declare r public.reservations%rowtype;provider_id uuid;begin select * into r from public.reservations where id=new.reservation_id;provider_id:=public.reservation_provider_user(r.professional_id,r.space_id);if tg_op='INSERT' then if provider_id is not null then perform public.push_notification(provider_id,'reservation','Novo pedido de alteração de reserva.','/dashboard/reservas',jsonb_build_object('reservation_id',r.id,'change_request_id',new.id),'reservation-change:'||new.id::text||':requested');end if;elsif old.status is distinct from new.status then perform public.push_notification(r.user_id,'reservation',case new.status when 'approved' then 'Alteração de reserva aprovada.' when 'rejected' then 'Alteração de reserva recusada.' else 'Pedido de alteração atualizado.' end,'/dashboard/agenda',jsonb_build_object('reservation_id',r.id,'change_request_id',new.id,'status',new.status),'reservation-change:'||new.id::text||':'||new.status);end if;return new;end $$;
drop trigger if exists notify_reservation_change_request on public.reservation_change_requests;create trigger notify_reservation_change_request after insert or update of status on public.reservation_change_requests for each row execute function public.notify_reservation_change_request();

create or replace function public.notify_event_participant_change() returns trigger language plpgsql security definer set search_path=public as $$ declare ev record;msg text;begin select id,title,created_by into ev from public.events where id=new.event_id;if tg_op='INSERT' and ev.created_by is not null and ev.created_by<>new.user_id then perform public.push_notification(ev.created_by,'event','Nova inscrição em '||coalesce(ev.title,'evento')||'.','/dashboard/eventos',jsonb_build_object('event_id',new.event_id,'participant_id',new.id),'event-participant:'||new.id::text||':organizer');end if;if tg_op='UPDATE' and(old.status is distinct from new.status or old.payment_status is distinct from new.payment_status) then msg:=case when new.payment_status='paid' then 'Pagamento do evento confirmado.' when new.status='confirmed' then 'Inscrição no evento confirmada.' when new.status='cancelled' then 'Inscrição no evento cancelada.' else 'Inscrição no evento atualizada.' end;perform public.push_notification(new.user_id,'event',msg,'/dashboard/agenda',jsonb_build_object('event_id',new.event_id,'participant_id',new.id,'status',new.status,'payment_status',new.payment_status),'event-participant:'||new.id::text||':'||new.status||':'||new.payment_status);end if;return new;end $$;
drop trigger if exists notify_event_participant_change on public.event_participants;create trigger notify_event_participant_change after insert or update of status,payment_status on public.event_participants for each row execute function public.notify_event_participant_change();

create or replace function public.notify_review_insert() returns trigger language plpgsql security definer set search_path=public as $$ declare target_user uuid;begin if new.professional_id is not null then select user_id into target_user from public.professionals where id=new.professional_id;elsif new.space_id is not null then select owner_user_id into target_user from public.sport_spaces where id=new.space_id;elsif new.event_id is not null then select created_by into target_user from public.events where id=new.event_id;end if;if target_user is not null and target_user<>new.user_id then perform public.push_notification(target_user,'review','Recebeste uma nova avaliação de '||new.rating::text||' estrelas.','/dashboard/avaliacoes',jsonb_build_object('review_id',new.id,'rating',new.rating),'review:'||new.id::text);end if;return new;end $$;
drop trigger if exists notify_review_insert on public.reviews;create trigger notify_review_insert after insert on public.reviews for each row execute function public.notify_review_insert();

create or replace function public.sync_reservation_thread_status() returns trigger language plpgsql security definer set search_path=public as $$ begin update public.message_threads set status=case when new.status::text in('paid','confirmed') and coalesce(new.payment_status,'') in('paid','') and(new.date::text||' '||new.end_time::text)::timestamp>(now() at time zone 'Europe/Lisbon') then 'active' else 'archived' end,archived_at=case when new.status::text in('paid','confirmed') and coalesce(new.payment_status,'') in('paid','') and(new.date::text||' '||new.end_time::text)::timestamp>(now() at time zone 'Europe/Lisbon') then null else now() end,updated_at=now() where reservation_id=new.id;return new;end $$;
drop trigger if exists sync_reservation_thread_status on public.reservations;create trigger sync_reservation_thread_status after update of status,payment_status,date,start_time,end_time on public.reservations for each row execute function public.sync_reservation_thread_status();

create or replace function public.ensure_event_default_ticket() returns trigger language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.event_ticket_types where event_id=new.id) then insert into public.event_ticket_types(event_id,name,price,sort_order) values(new.id,'Entrada',coalesce(new.price_min,0),0);end if;return new;end $$;
drop trigger if exists ensure_event_default_ticket on public.events;create trigger ensure_event_default_ticket after insert on public.events for each row execute function public.ensure_event_default_ticket();
create or replace function public.assign_default_event_ticket() returns trigger language plpgsql security definer set search_path=public as $$ declare ticket record;begin if new.ticket_type_id is null then select id,price into ticket from public.event_ticket_types where event_id=new.event_id and is_active=true order by sort_order,id limit 1;if ticket.id is not null then new.ticket_type_id:=ticket.id;if new.amount is null then new.amount:=ticket.price;end if;end if;elsif new.amount is null then select price into new.amount from public.event_ticket_types where id=new.ticket_type_id and event_id=new.event_id;end if;return new;end $$;
drop trigger if exists assign_default_event_ticket on public.event_participants;create trigger assign_default_event_ticket before insert on public.event_participants for each row execute function public.assign_default_event_ticket();

update public.platform_users pu set type='professional'::public.user_role,updated_at=now() where exists(select 1 from public.professionals p where p.user_id=pu.id) and pu.type='athlete'::public.user_role;
update public.platform_users pu set type='venue_manager'::public.user_role,updated_at=now() where exists(select 1 from public.sport_spaces s where s.owner_user_id=pu.id) and pu.type='athlete'::public.user_role;
create or replace function public.enforce_provider_identity() returns trigger language plpgsql security definer set search_path=public as $$ declare current_role public.user_role;begin if tg_table_name='professionals' then select type into current_role from public.platform_users where id=new.user_id for update;if current_role='venue_manager' then raise exception 'A venue manager account cannot also own a professional profile';end if;if current_role is distinct from 'professional'::public.user_role then update public.platform_users set type='professional',updated_at=now() where id=new.user_id;end if;elsif tg_table_name='sport_spaces' and new.owner_user_id is not null then select type into current_role from public.platform_users where id=new.owner_user_id for update;if current_role='professional' then raise exception 'A professional account cannot also own a venue with the current single-role model';end if;if current_role is distinct from 'venue_manager'::public.user_role then update public.platform_users set type='venue_manager',updated_at=now() where id=new.owner_user_id;end if;end if;return new;end $$;
drop trigger if exists enforce_professional_identity on public.professionals;create trigger enforce_professional_identity before insert or update of user_id on public.professionals for each row execute function public.enforce_provider_identity();drop trigger if exists enforce_space_owner_identity on public.sport_spaces;create trigger enforce_space_owner_identity before insert or update of owner_user_id on public.sport_spaces for each row execute function public.enforce_provider_identity();

do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then alter publication supabase_realtime add table public.messages;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='message_threads') then alter publication supabase_realtime add table public.message_threads;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then alter publication supabase_realtime add table public.notifications;end if;end $$;
