import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { CurrentPlanSummary } from '@/components/dashboard/current-plan-summary'
import { OverviewDashboard } from '@/components/dashboard/overview-dashboard'
import { resolveSessionAccess } from '@/lib/auth/access'

async function getSubscriptionContext(supabase:Awaited<ReturnType<typeof createClient>>,userId:string,audience:'professional'|'venue_manager'){
 const{data:subscription}=await supabase.from('user_subscriptions').select('tier,status,plan_id,current_period_end,cancel_at_period_end').eq('user_id',userId).maybeSingle();const tier=subscription?.tier||'free';let plan:any=null;if(subscription?.plan_id)plan=(await supabase.from('subscription_plans').select('id,code,name,commission_rate').eq('id',subscription.plan_id).maybeSingle()).data;if(!plan)plan=(await supabase.from('subscription_plans').select('id,code,name,commission_rate').eq('audience',audience).eq('code',tier).maybeSingle()).data;return{tier,subscription,plan:plan||{name:tier==='free'?'Grátis':tier,commission_rate:null}}
}

export default async function DashboardPage({searchParams}:{searchParams:Promise<{space?:string}>}){
 const filters=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/auth/login?redirect=/dashboard');const access=await resolveSessionAccess(supabase,user);if(!access?.canAccessDashboard)redirect('/auth/login?redirect=/dashboard')
 if(access.role==='athlete'){const{data:profile}=await supabase.from('platform_users').select('full_name').eq('id',user.id).maybeSingle();const displayName=profile?.full_name?.split(' ')[0]||user.user_metadata?.full_name?.split(' ')[0]||'Atleta';return <OverviewDashboard role="athlete" userId={user.id} displayName={displayName}/>} 
 if(access.role==='professional'){const[{data:professional},billing]=await Promise.all([supabase.from('professionals').select('*').eq('user_id',user.id).maybeSingle(),getSubscriptionContext(supabase,user.id,'professional')]);if(!professional)redirect('/auth/registar/profissional');return <><CurrentPlanSummary planName={billing.plan.name} tier={billing.tier} commissionRate={billing.plan.commission_rate} status={billing.subscription?.status} currentPeriodEnd={billing.subscription?.current_period_end} cancelAtPeriodEnd={billing.subscription?.cancel_at_period_end}/><OverviewDashboard role="professional" userId={user.id} displayName={professional.full_name?.split(' ')[0]||'Profissional'} entity={professional}/></>}
 const[{data:spaces},billing]=await Promise.all([supabase.from('sport_spaces').select('*').eq('owner_user_id',user.id).order('name'),getSubscriptionContext(supabase,user.id,'venue_manager')]);if(!spaces?.length)redirect('/auth/registar/espaco');const selected=filters.space?spaces.find(s=>s.id===filters.space):null;return <><CurrentPlanSummary planName={billing.plan.name} tier={billing.tier} commissionRate={billing.plan.commission_rate} status={billing.subscription?.status} currentPeriodEnd={billing.subscription?.current_period_end} cancelAtPeriodEnd={billing.subscription?.cancel_at_period_end}/><OverviewDashboard role="venue_manager" userId={user.id} displayName={selected?.name||'Gestor'} entity={selected||null} entities={spaces} selectedEntityId={selected?.id||null}/></>
}
